// AUTO-GENERATED by scripts/codegen/generate-contract-types.mjs.
// Do not edit by hand; run npm run codegen:types.

export type ChainsRow = {
  "id": string;
  "name": string;
  "retailer_type": string;
  "domain": string;
  "country_code": string;
  "created_at": string;
};

export type StoresRow = {
  "id": string;
  "chain_id": string;
  "name": string;
  "address": string;
  "city": string;
  "district": string | null;
  "domain": string;
  "latitude": number | null;
  "longitude": number | null;
  "store_type": string | null;
  "opening_hours": Record<string, unknown> | null;
  "online_store_id": string | null;
  "created_at": string;
};

export type CategoriesRow = {
  "id": string;
  "parent_id": string | null;
  "name": string;
};

export type ProductsRow = {
  "id": string;
  "barcode": string | null;
  "canonical_name": string;
  "name_sv": string | null;
  "name_en": string | null;
  "domain": string;
  "fuel_grade_id": string | null;
  "brand": string | null;
  "brand_owner": string | null;
  "private_label_owner": string | null;
  "category_id": string | null;
  "subcategory_id": string | null;
  "package_size": number | null;
  "package_unit": string | null;
  "comparable_unit": string;
  "organic": boolean;
  "lactose_free": boolean;
  "gluten_free": boolean;
  "vegan": boolean;
  "image_url": string | null;
  "nutrition_source": string | null;
  "created_at": string;
};

export type AnalyticsEventsRow = {
  "id": string;
  "event_name": string;
  "product_id": string | null;
  "anonymous_id": string | null;
  "metadata": Record<string, unknown>;
  "occurred_at": string;
};

export type ProductAliasesRow = {
  "id": number;
  "raw_name": string;
  "source_type": string;
  "matched_product_id": string | null;
  "match_confidence": number;
  "reviewed_by_human": boolean;
  "created_at": string;
};

export type PriceObservationsRow = {
  "id": number;
  "product_id": string;
  "retailer_product_id": string | null;
  "store_id": string | null;
  "chain_id": string;
  "domain": string;
  "observed_at": string;
  "price": number;
  "unit_price": number;
  "currency": string;
  "regular_price": number | null;
  "promo_price": number | null;
  "member_price": number | null;
  "promo_type": string | null;
  "source_type": string;
  "source_url": string | null;
  "origin_country": string | null;
  "cert_level": string | null;
  "confidence_score": number;
  "is_online_price": boolean;
  "is_instore_price": boolean;
  "created_at": string;
};

export type PromotionObservationsRow = {
  "id": number;
  "product_id": string;
  "chain_id": string;
  "store_id": string | null;
  "promo_start": string | null;
  "promo_end": string | null;
  "promo_price": number;
  "regular_price_claimed": number | null;
  "promo_text": string | null;
  "member_only": boolean;
  "multi_buy_quantity": number | null;
  "multi_buy_price": number | null;
  "source_type": string;
  "confidence_score": number;
  "created_at": string;
};

export type AppUsersRow = {
  "id": string;
  "email": string | null;
  "created_at": string;
};

export type SubscriptionEntitlementsRow = {
  "user_id": string;
  "tier": string;
  "plan": string | null;
  "status": string;
  "current_period_ends_at": string | null;
  "provider": string | null;
  "provider_customer_id": string | null;
  "provider_subscription_id": string | null;
  "updated_at": string;
};

export type UserPreferencesRow = {
  "id": number;
  "user_id": string | null;
  "session_id": string | null;
  "country": string;
  "favorite_stores": string[];
  "home_lat": number | null;
  "home_lng": number | null;
  "household_size": number | null;
  "diet_filters": string[];
  "algorithm_choice": string;
  "weekly_budget": number | null;
  "monthly_budget": number | null;
  "accept_private_label": string;
  "accept_budget_private_label": string;
  "include_member_prices": boolean;
  "preferred_language": string;
  "preferred_currency": string;
  "dietary_preferences": Record<string, unknown>;
  "notification_preferences": Record<string, unknown>;
  "created_at": string;
  "updated_at": string;
};

export type FavoriteStoresRow = {
  "user_id": string;
  "store_id": string;
  "label": string | null;
  "created_at": string;
};

export type WatchlistItemsRow = {
  "id": number;
  "user_id": string;
  "product_id": string | null;
  "category_id": string | null;
  "target_price": number | null;
  "preferred_brands": string[];
  "accept_private_label": string;
  "organic_only": boolean;
  "alert_deal_score_at": number | null;
  "favorite_stores_only": boolean;
  "stock_up_allowed": boolean;
  "created_at": string;
};

export type WebhookSubscriptionsRow = {
  "id": string;
  "user_id": string | null;
  "product_id": string | null;
  "chain": string | null;
  "callback_url": string;
  "secret": string | null;
  "active": boolean;
  "last_delivery_at": string | null;
  "failure_count": number;
  "created_at": string;
  "updated_at": string;
};

export type WeeklyBasketsRow = {
  "id": number;
  "user_id": string;
  "household_id": string | null;
  "week_start": string;
  "budget": number | null;
  "status": string;
  "created_at": string;
};

export type BasketItemsRow = {
  "id": number;
  "basket_id": number;
  "product_id": string | null;
  "raw_name": string | null;
  "quantity": number;
  "preferred_brand": string | null;
  "substitution_mode": string;
  "marked_bought": boolean;
  "created_at": string;
};

export type BudgetsRow = {
  "id": number;
  "user_id": string;
  "period": string;
  "amount": number;
  "category_id": string | null;
  "starts_on": string;
  "ends_on": string;
  "created_at": string;
};

export type ReceiptUploadsRow = {
  "id": number;
  "user_id": string;
  "store_id": string | null;
  "purchased_at": string | null;
  "total_amount": number;
  "image_url": string | null;
  "ocr_confidence": number | null;
  "created_at": string;
};

export type ReceiptItemsRow = {
  "id": number;
  "receipt_id": number;
  "raw_name": string;
  "product_id": string | null;
  "quantity": number | null;
  "item_total": number;
  "discounts": number | null;
  "member_price": number | null;
  "match_confidence": number | null;
};

export type CommunityPriceReportsRow = {
  "id": number;
  "user_id": string | null;
  "product_id": string | null;
  "store_id": string | null;
  "observed_at": string;
  "price": number;
  "source_type": string;
  "photo_url": string | null;
  "confidence_score": number;
  "review_status": string;
};

export type CommunityReporterTrustRow = {
  "reporter_id": string;
  "reports_last_24_hours": number;
  "pending_reports": number;
  "accepted_reports_last_30_days": number;
  "rejected_reports_last_30_days": number;
  "updated_at": string;
};

export type FuelGradesRow = {
  "id": string;
  "grade_code": string;
  "label": string;
  "comparable_unit": string;
  "match_key": string;
  "active": boolean;
  "created_at": string;
};

export type FuelPriceSourcesRow = {
  "id": number;
  "source_kind": string;
  "operator_id": string | null;
  "operator_name": string | null;
  "station_id": string | null;
  "reporter_id": string | null;
  "reporter_trust_tier": string | null;
  "evidence_type": string | null;
  "source_url": string | null;
  "parser_version": string | null;
  "captured_at": string | null;
  "submitted_at": string | null;
  "provenance": Record<string, unknown>;
  "created_at": string;
  "and": unknown;
  "and": unknown;
  "and": unknown;
  "and": unknown;
  "and": unknown;
  "and": unknown | null;
  "and": unknown | null;
  "and": unknown | null;
  "and": unknown;
  "and": unknown;
  "and": unknown;
  "and": unknown;
  "and": unknown;
};

export type FuelPriceSourceObservationsRow = {
  "source_id": number;
  "price_observation_id": number;
  "fuel_grade_id": string;
  "original_price_text": string;
  "original_effective_date": string | null;
  "created_at": string;
};

export type NotificationTasksRow = {
  "id": string;
  "channel": string;
  "type": string;
  "title": string;
  "body": string;
  "priority": string;
  "send_at": string;
  "recipient": string;
  "attempt_count": number;
  "max_attempts": number;
  "status": string;
  "created_at": string;
  "updated_at": string;
};

export type NotificationSuppressionsRow = {
  "id": string;
  "recipient": string;
  "channel": string | null;
  "reason": string;
  "active": boolean;
  "updated_at": string;
};

export type NotificationSubscriptionsRow = {
  "id": string;
  "user_id": string;
  "channel": string;
  "recipient": string;
  "chat_id": string | null;
  "product_id": string | null;
  "active": boolean;
  "created_at": string;
  "updated_at": string;
};

export type HumanReviewersRow = {
  "id": string;
  "role": string;
  "active": boolean;
  "created_at": string;
  "updated_at": string;
};

export type HumanReviewAssignmentsRow = {
  "id": string;
  "review_id": string;
  "subject_type": string;
  "subject_id": string;
  "priority": string;
  "reason": string;
  "assignee_id": string;
  "assigned_at": string;
  "due_at": string;
  "status": string;
  "created_at": string;
  "updated_at": string;
};

export type GroceryIndicesRow = {
  "id": string;
  "label": string;
  "scope_type": string;
  "scope_id": string | null;
  "base_date": string;
  "methodology": string;
  "confidence_score": number;
  "created_at": string;
};

export type GroceryIndexComponentsRow = {
  "index_id": string;
  "product_id": string;
  "weight": number;
  "comparable_unit": string;
};

export type ProduceClassesRow = {
  "id": string;
  "parent_id": string | null;
  "segment": string;
  "label": string;
  "depth": number;
  "sort_order": number;
  "created_at": string;
  "updated_at": string;
};

export type GeneratedDbTableName = 'chains' | 'stores' | 'categories' | 'products' | 'analytics_events' | 'product_aliases' | 'price_observations' | 'promotion_observations' | 'app_users' | 'subscription_entitlements' | 'user_preferences' | 'favorite_stores' | 'watchlist_items' | 'webhook_subscriptions' | 'weekly_baskets' | 'basket_items' | 'budgets' | 'receipt_uploads' | 'receipt_items' | 'community_price_reports' | 'community_reporter_trust' | 'fuel_grades' | 'fuel_price_sources' | 'fuel_price_source_observations' | 'notification_tasks' | 'notification_suppressions' | 'notification_subscriptions' | 'human_reviewers' | 'human_review_assignments' | 'grocery_indices' | 'grocery_index_components' | 'produce_classes';

export type GeneratedDatabaseRows = {
  "chains": ChainsRow;
  "stores": StoresRow;
  "categories": CategoriesRow;
  "products": ProductsRow;
  "analytics_events": AnalyticsEventsRow;
  "product_aliases": ProductAliasesRow;
  "price_observations": PriceObservationsRow;
  "promotion_observations": PromotionObservationsRow;
  "app_users": AppUsersRow;
  "subscription_entitlements": SubscriptionEntitlementsRow;
  "user_preferences": UserPreferencesRow;
  "favorite_stores": FavoriteStoresRow;
  "watchlist_items": WatchlistItemsRow;
  "webhook_subscriptions": WebhookSubscriptionsRow;
  "weekly_baskets": WeeklyBasketsRow;
  "basket_items": BasketItemsRow;
  "budgets": BudgetsRow;
  "receipt_uploads": ReceiptUploadsRow;
  "receipt_items": ReceiptItemsRow;
  "community_price_reports": CommunityPriceReportsRow;
  "community_reporter_trust": CommunityReporterTrustRow;
  "fuel_grades": FuelGradesRow;
  "fuel_price_sources": FuelPriceSourcesRow;
  "fuel_price_source_observations": FuelPriceSourceObservationsRow;
  "notification_tasks": NotificationTasksRow;
  "notification_suppressions": NotificationSuppressionsRow;
  "notification_subscriptions": NotificationSubscriptionsRow;
  "human_reviewers": HumanReviewersRow;
  "human_review_assignments": HumanReviewAssignmentsRow;
  "grocery_indices": GroceryIndicesRow;
  "grocery_index_components": GroceryIndexComponentsRow;
  "produce_classes": ProduceClassesRow;
};

export type GeneratedApiContractName = 'alert' | 'basket' | 'basketItem' | 'compareItemIds' | 'compareMissingItemIds' | 'comparePriceSnapshot' | 'compareResponse' | 'compareStoreItemPrices' | 'compareStores' | 'confidence' | 'dealShareRelationship' | 'friendSharedDealSignal' | 'friendSharedDealSignalCreate' | 'friendSharedDealSignalListResponse' | 'fuelGrade' | 'fuelPriceObservation' | 'fuelPriceSource' | 'fuelPricesResponse' | 'latestPrice' | 'moneyAmount' | 'multiWeekStockUpConfidence' | 'multiWeekStockUpCreateRow' | 'multiWeekStockUpListResponse' | 'multiWeekStockUpRow' | 'multiWeekStockUpUpdateRow' | 'notificationInboxQueueItem' | 'notificationInboxResponse' | 'notificationInboxSummary' | 'priceDomain' | 'priceObservation' | 'priceType' | 'product' | 'productPricesResponse' | 'provenance' | 'sourceType' | 'store' | 'watchlist';

export type GeneratedApiContractDtoNames = {
  alert: 'AlertDto';
  basket: 'BasketDto';
  basketItem: 'BasketItemDto';
  compareItemIds: 'CompareItemIdsDto';
  compareMissingItemIds: 'CompareMissingItemIdsDto';
  comparePriceSnapshot: 'ComparePriceSnapshotDto';
  compareResponse: 'CompareResponseDto';
  compareStoreItemPrices: 'CompareStoreItemPricesDto';
  compareStores: 'CompareStoresDto';
  confidence: 'ConfidenceDto';
  dealShareRelationship: 'DealShareRelationshipDto';
  friendSharedDealSignal: 'FriendSharedDealSignalDto';
  friendSharedDealSignalCreate: 'FriendSharedDealSignalCreateDto';
  friendSharedDealSignalListResponse: 'FriendSharedDealSignalListResponseDto';
  fuelGrade: 'FuelGradeDto';
  fuelPriceObservation: 'FuelPriceObservationDto';
  fuelPriceSource: 'FuelPriceSourceDto';
  fuelPricesResponse: 'FuelPricesResponseDto';
  latestPrice: 'LatestPriceDto';
  moneyAmount: 'MoneyAmountDto';
  multiWeekStockUpConfidence: 'MultiWeekStockUpConfidenceDto';
  multiWeekStockUpCreateRow: 'MultiWeekStockUpCreateRowDto';
  multiWeekStockUpListResponse: 'MultiWeekStockUpListResponseDto';
  multiWeekStockUpRow: 'MultiWeekStockUpRowDto';
  multiWeekStockUpUpdateRow: 'MultiWeekStockUpUpdateRowDto';
  notificationInboxQueueItem: 'NotificationInboxQueueItemDto';
  notificationInboxResponse: 'NotificationInboxResponseDto';
  notificationInboxSummary: 'NotificationInboxSummaryDto';
  priceDomain: 'PriceDomainDto';
  priceObservation: 'PriceObservationDto';
  priceType: 'PriceTypeDto';
  product: 'ProductDto';
  productPricesResponse: 'ProductPricesResponseDto';
  provenance: 'ProvenanceDto';
  sourceType: 'SourceTypeDto';
  store: 'StoreDto';
  watchlist: 'WatchlistDto';
};
