import { EntitySchema } from 'typeorm';
import type { EntitySchemaColumnOptions } from 'typeorm';
import { alertStatuses, confidenceBands, observationStatuses, priceTypes, sourceTypes } from './enums';
import type { AlertStatus, ConfidenceBand, ObservationStatus, PriceType, SourceType } from './enums';

type JsonObject = Record<string, unknown>;

export interface City { id: string; name: string; countryCode: string; currencyCode: string; timezone: string; locale: string; createdAt: Date; }
export interface Chain { id: string; name: string; slug: string; countryCode: string; websiteUrl: string | null; createdAt: Date; }
export interface Store { id: string; chainId: string; cityId: string; name: string; slug: string; address: string; district: string | null; postalCode: string | null; latitude: string | null; longitude: string | null; location: unknown | null; retailerStoreId: string | null; openingHours: JsonObject | null; isActive: boolean; createdAt: Date; updatedAt: Date; }
export interface Product { id: string; ean: string | null; name: string; slug: string; brand: string | null; category: string; subcategory: string | null; unit: string; unitSize: string | null; unitQuantityText: string | null; packageSize: string | null; nutrition: JsonObject | null; imageUrl: string | null; isPrivateLabel: boolean; createdAt: Date; updatedAt: Date; }
export interface ProductAlias { id: string; productId: string; alias: string; sourceType: SourceType; createdAt: Date; }
export interface SourceRun { id: string; sourceType: SourceType; sourceName: string; startedAt: Date; finishedAt: Date | null; status: ObservationStatus; parserVersion: string; metadata: JsonObject; }
export interface SourceRecordRaw { id: string; sourceRunId: string | null; sourceType: SourceType; sourceUrl: string | null; storageUri: string | null; recordHash: string | null; payload: JsonObject | null; fetchedAt: Date; parserVersion: string | null; confidenceScore: string | null; }
export interface PriceObservation { id: string; productId: string; storeId: string | null; cityId: string; chainId: string | null; priceType: PriceType; priceSek: string; regularPriceSek: string | null; memberPriceSek: string | null; unitPriceSek: string | null; unitPriceUnit: string | null; currencyCode: string; observedAt: Date; validFrom: Date | null; validTo: Date | null; sourceType: SourceType; sourceUrl: string | null; sourceRunId: string | null; rawRecordId: string | null; parserVersion: string; confidenceScore: string; confidenceBand: ConfidenceBand; status: ObservationStatus; createdAt: Date; }
export interface PromotionObservation { id: string; productId: string; storeId: string | null; cityId: string; chainId: string | null; promoPriceSek: string; regularPriceSek: string | null; unitPriceSek: string | null; unitPriceUnit: string | null; promoStart: string | null; promoEnd: string | null; memberOnly: boolean; promotionText: string | null; sourceType: SourceType; sourceUrl: string | null; sourceRunId: string | null; rawRecordId: string | null; observedAt: Date; parserVersion: string; confidenceScore: string; confidenceBand: ConfidenceBand; status: ObservationStatus; createdAt: Date; }
export interface LatestStorePrice { id: string; productId: string; storeId: string; cityId: string; chainId: string | null; priceObservationId: string | null; priceType: PriceType; priceSek: string; regularPriceSek: string | null; memberPriceSek: string | null; unitPriceSek: string | null; unitPriceUnit: string | null; observedAt: Date; sourceType: SourceType; sourceUrl: string | null; sourceRunId: string | null; rawRecordId: string | null; parserVersion: string; confidenceScore: string; confidenceBand: ConfidenceBand; updatedAt: Date; }
export interface User { id: string; email: string; displayName: string | null; homeCityId: string | null; createdAt: Date; updatedAt: Date; }
export interface FavoriteStore { userId: string; storeId: string; createdAt: Date; }
export interface WatchlistItem { id: string; userId: string; productId: string; targetPriceSek: string | null; thresholdPct: string | null; includeMemberPrices: boolean; status: AlertStatus; createdAt: Date; updatedAt: Date; }

const id = { type: 'bigint', primary: true, generated: 'increment' } satisfies EntitySchemaColumnOptions;
const createdAt = { name: 'created_at', type: 'timestamptz', createDate: true } satisfies EntitySchemaColumnOptions;
const updatedAt = { name: 'updated_at', type: 'timestamptz', updateDate: true } satisfies EntitySchemaColumnOptions;
const money = { type: 'numeric', precision: 12, scale: 2 } satisfies EntitySchemaColumnOptions;
const score = { name: 'confidence_score', type: 'numeric', precision: 5, scale: 4 } satisfies EntitySchemaColumnOptions;

export const CityEntity = new EntitySchema<City>({ name: 'City', tableName: 'cities', columns: { id, name: { type: 'text' }, countryCode: { name: 'country_code', type: 'char', length: 2 }, currencyCode: { name: 'currency_code', type: 'char', length: 3, default: 'SEK' }, timezone: { type: 'text', default: 'Europe/Stockholm' }, locale: { type: 'text', default: 'sv-SE' }, createdAt } });
export const ChainEntity = new EntitySchema<Chain>({ name: 'Chain', tableName: 'chains', columns: { id, name: { type: 'text', unique: true }, slug: { type: 'text', unique: true }, countryCode: { name: 'country_code', type: 'char', length: 2, default: 'SE' }, websiteUrl: { name: 'website_url', type: 'text', nullable: true }, createdAt } });
export const StoreEntity = new EntitySchema<Store>({ name: 'Store', tableName: 'stores', columns: { id, chainId: { name: 'chain_id', type: 'bigint' }, cityId: { name: 'city_id', type: 'bigint' }, name: { type: 'text' }, slug: { type: 'text', unique: true }, address: { type: 'text' }, district: { type: 'text', nullable: true }, postalCode: { name: 'postal_code', type: 'text', nullable: true }, latitude: { type: 'numeric', precision: 9, scale: 6, nullable: true }, longitude: { type: 'numeric', precision: 9, scale: 6, nullable: true }, location: { type: 'geography', spatialFeatureType: 'Point', srid: 4326, nullable: true }, retailerStoreId: { name: 'retailer_store_id', type: 'text', nullable: true }, openingHours: { name: 'opening_hours', type: 'jsonb', nullable: true }, isActive: { name: 'is_active', type: 'boolean', default: true }, createdAt, updatedAt } });
export const ProductEntity = new EntitySchema<Product>({ name: 'Product', tableName: 'products', columns: { id, ean: { type: 'text', nullable: true, unique: true }, name: { type: 'text' }, slug: { type: 'text', unique: true }, brand: { type: 'text', nullable: true }, category: { type: 'text' }, subcategory: { type: 'text', nullable: true }, unit: { type: 'text' }, unitSize: { name: 'unit_size', type: 'numeric', precision: 12, scale: 3, nullable: true }, unitQuantityText: { name: 'unit_quantity_text', type: 'text', nullable: true }, packageSize: { name: 'package_size', type: 'text', nullable: true }, nutrition: { type: 'jsonb', nullable: true }, imageUrl: { name: 'image_url', type: 'text', nullable: true }, isPrivateLabel: { name: 'is_private_label', type: 'boolean', default: false }, createdAt, updatedAt } });
export const ProductAliasEntity = new EntitySchema<ProductAlias>({ name: 'ProductAlias', tableName: 'product_aliases', columns: { id, productId: { name: 'product_id', type: 'bigint' }, alias: { type: 'text' }, sourceType: { name: 'source_type', type: 'enum', enum: sourceTypes, default: 'manual_admin' }, createdAt } });
export const SourceRunEntity = new EntitySchema<SourceRun>({ name: 'SourceRun', tableName: 'source_runs', columns: { id, sourceType: { name: 'source_type', type: 'enum', enum: sourceTypes }, sourceName: { name: 'source_name', type: 'text' }, startedAt: { name: 'started_at', type: 'timestamptz', createDate: true }, finishedAt: { name: 'finished_at', type: 'timestamptz', nullable: true }, status: { type: 'enum', enum: observationStatuses, default: 'pending' }, parserVersion: { name: 'parser_version', type: 'text' }, metadata: { type: 'jsonb', default: {} } } });
export const SourceRecordRawEntity = new EntitySchema<SourceRecordRaw>({ name: 'SourceRecordRaw', tableName: 'source_records_raw', columns: { id, sourceRunId: { name: 'source_run_id', type: 'bigint', nullable: true }, sourceType: { name: 'source_type', type: 'enum', enum: sourceTypes }, sourceUrl: { name: 'source_url', type: 'text', nullable: true }, storageUri: { name: 'storage_uri', type: 'text', nullable: true }, recordHash: { name: 'record_hash', type: 'text', nullable: true, unique: true }, payload: { type: 'jsonb', nullable: true }, fetchedAt: { name: 'fetched_at', type: 'timestamptz', createDate: true }, parserVersion: { name: 'parser_version', type: 'text', nullable: true }, confidenceScore: { ...score, nullable: true } } });
export const PriceObservationEntity = new EntitySchema<PriceObservation>({ name: 'PriceObservation', tableName: 'price_observations', columns: { id, productId: { name: 'product_id', type: 'bigint' }, storeId: { name: 'store_id', type: 'bigint', nullable: true }, cityId: { name: 'city_id', type: 'bigint' }, chainId: { name: 'chain_id', type: 'bigint', nullable: true }, priceType: { name: 'price_type', type: 'enum', enum: priceTypes }, priceSek: { name: 'price_sek', ...money }, regularPriceSek: { name: 'regular_price_sek', ...money, nullable: true }, memberPriceSek: { name: 'member_price_sek', ...money, nullable: true }, unitPriceSek: { name: 'unit_price_sek', ...money, nullable: true }, unitPriceUnit: { name: 'unit_price_unit', type: 'text', nullable: true }, currencyCode: { name: 'currency_code', type: 'char', length: 3, default: 'SEK' }, observedAt: { name: 'observed_at', type: 'timestamptz' }, validFrom: { name: 'valid_from', type: 'timestamptz', nullable: true }, validTo: { name: 'valid_to', type: 'timestamptz', nullable: true }, sourceType: { name: 'source_type', type: 'enum', enum: sourceTypes }, sourceUrl: { name: 'source_url', type: 'text', nullable: true }, sourceRunId: { name: 'source_run_id', type: 'bigint', nullable: true }, rawRecordId: { name: 'raw_record_id', type: 'bigint', nullable: true }, parserVersion: { name: 'parser_version', type: 'text' }, confidenceScore: score, confidenceBand: { name: 'confidence_band', type: 'enum', enum: confidenceBands }, status: { type: 'enum', enum: observationStatuses, default: 'accepted' }, createdAt } });
export const PromotionObservationEntity = new EntitySchema<PromotionObservation>({ name: 'PromotionObservation', tableName: 'promotion_observations', columns: { id, productId: { name: 'product_id', type: 'bigint' }, storeId: { name: 'store_id', type: 'bigint', nullable: true }, cityId: { name: 'city_id', type: 'bigint' }, chainId: { name: 'chain_id', type: 'bigint', nullable: true }, promoPriceSek: { name: 'promo_price_sek', ...money }, regularPriceSek: { name: 'regular_price_sek', ...money, nullable: true }, unitPriceSek: { name: 'unit_price_sek', ...money, nullable: true }, unitPriceUnit: { name: 'unit_price_unit', type: 'text', nullable: true }, promoStart: { name: 'promo_start', type: 'date', nullable: true }, promoEnd: { name: 'promo_end', type: 'date', nullable: true }, memberOnly: { name: 'member_only', type: 'boolean', default: false }, promotionText: { name: 'promotion_text', type: 'text', nullable: true }, sourceType: { name: 'source_type', type: 'enum', enum: sourceTypes }, sourceUrl: { name: 'source_url', type: 'text', nullable: true }, sourceRunId: { name: 'source_run_id', type: 'bigint', nullable: true }, rawRecordId: { name: 'raw_record_id', type: 'bigint', nullable: true }, observedAt: { name: 'observed_at', type: 'timestamptz' }, parserVersion: { name: 'parser_version', type: 'text' }, confidenceScore: score, confidenceBand: { name: 'confidence_band', type: 'enum', enum: confidenceBands }, status: { type: 'enum', enum: observationStatuses, default: 'accepted' }, createdAt } });
export const LatestStorePriceEntity = new EntitySchema<LatestStorePrice>({ name: 'LatestStorePrice', tableName: 'latest_store_prices', columns: { id, productId: { name: 'product_id', type: 'bigint' }, storeId: { name: 'store_id', type: 'bigint' }, cityId: { name: 'city_id', type: 'bigint' }, chainId: { name: 'chain_id', type: 'bigint', nullable: true }, priceObservationId: { name: 'price_observation_id', type: 'bigint', nullable: true }, priceType: { name: 'price_type', type: 'enum', enum: priceTypes }, priceSek: { name: 'price_sek', ...money }, regularPriceSek: { name: 'regular_price_sek', ...money, nullable: true }, memberPriceSek: { name: 'member_price_sek', ...money, nullable: true }, unitPriceSek: { name: 'unit_price_sek', ...money, nullable: true }, unitPriceUnit: { name: 'unit_price_unit', type: 'text', nullable: true }, observedAt: { name: 'observed_at', type: 'timestamptz' }, sourceType: { name: 'source_type', type: 'enum', enum: sourceTypes }, sourceUrl: { name: 'source_url', type: 'text', nullable: true }, sourceRunId: { name: 'source_run_id', type: 'bigint', nullable: true }, rawRecordId: { name: 'raw_record_id', type: 'bigint', nullable: true }, parserVersion: { name: 'parser_version', type: 'text' }, confidenceScore: score, confidenceBand: { name: 'confidence_band', type: 'enum', enum: confidenceBands }, updatedAt } });
export const UserEntity = new EntitySchema<User>({ name: 'User', tableName: 'users', columns: { id, email: { type: 'text', unique: true }, displayName: { name: 'display_name', type: 'text', nullable: true }, homeCityId: { name: 'home_city_id', type: 'bigint', nullable: true }, createdAt, updatedAt } });
export const FavoriteStoreEntity = new EntitySchema<FavoriteStore>({ name: 'FavoriteStore', tableName: 'favorite_stores', columns: { userId: { name: 'user_id', type: 'bigint', primary: true }, storeId: { name: 'store_id', type: 'bigint', primary: true }, createdAt } });
export const WatchlistItemEntity = new EntitySchema<WatchlistItem>({ name: 'WatchlistItem', tableName: 'watchlist_items', columns: { id, userId: { name: 'user_id', type: 'bigint' }, productId: { name: 'product_id', type: 'bigint' }, targetPriceSek: { name: 'target_price_sek', ...money, nullable: true }, thresholdPct: { name: 'threshold_pct', type: 'numeric', precision: 6, scale: 3, nullable: true }, includeMemberPrices: { name: 'include_member_prices', type: 'boolean', default: true }, status: { type: 'enum', enum: alertStatuses, default: 'active' }, createdAt, updatedAt } });

export const groceryViewEntities = [CityEntity, ChainEntity, StoreEntity, ProductEntity, ProductAliasEntity, SourceRunEntity, SourceRecordRawEntity, PriceObservationEntity, PromotionObservationEntity, LatestStorePriceEntity, UserEntity, FavoriteStoreEntity, WatchlistItemEntity] as const;
