// AUTO-GENERATED by apps/web/scripts/generate-db-site-snapshot.mjs.
// Build-time snapshot of Postgres latest_prices and observations for static web rendering.

export type PriceObservation = { price: number; date: string };
export type PricedProduct = {
  code: string; slug: string; name: string; brands: string; image: string;
  quantity: string; nutriscore: string; category: string;
  categories: string[];
  priceMin: number; priceMedian: number; priceMax: number;
  observationCount: number; lastObservedAt: string;
  observations: PriceObservation[];
};

export type DbLatestPrice = {
  code: string;
  productSlug: string;
  productName: string;
  brand: string;
  imageUrl: string;
  chainSlug: string;
  chainName: string;
  storeSlug: string | null;
  storeName: string | null;
  price: number;
  regularPrice: number | null;
  unitPrice: number | null;
  currency: string;
  priceType: string;
  observedAt: string;
  confidence: number;
  quantity: number | null;
  quantityUnit: string | null;
  promotionText: string | null;
  memberRequired: boolean;
  retailerProductRef: string | null;
  provenance: Record<string, unknown>;
};

export type DbSourceSummary = {
  source: string;
  label: string;
  rowCount: number;
  retrievedAt: string;
};

export type DbSiteSnapshotMeta = {
  generatedAt: string;
  source: 'postgres' | 'fallback';
  latestPriceCount: number;
  pricedProductCount: number;
  observationCount: number;
  newestObservedAt: string | null;
};

export const categoryLabels: Record<string,string> = {
  "dairy": "Dairy",
  "breakfast": "Breakfast",
  "bread": "Bread & Bakery",
  "beverages": "Beverages",
  "coffee-tea": "Coffee & Tea",
  "snacks": "Snacks",
  "sweets": "Sweets & Ice cream",
  "meat": "Meat & Charcuterie",
  "fish": "Fish & Seafood",
  "produce": "Fruit & Vegetables",
  "frozen": "Frozen",
  "pantry": "Pantry",
  "plant-based": "Plant-based",
  "alcohol": "Wine, Beer & Spirits",
  "baby": "Baby",
  "pet": "Pet",
  "household": "Cleaning & Household",
  "personal-care": "Personal care"
};

export const dbSiteSnapshotMeta: DbSiteSnapshotMeta = {
  "generatedAt": "1970-01-01T00:00:00.000Z",
  "source": "fallback",
  "latestPriceCount": 0,
  "pricedProductCount": 0,
  "observationCount": 0,
  "newestObservedAt": null
};

export const dbSourceSummaries: DbSourceSummary[] = [];

export const dbLatestPrices: DbLatestPrice[] = [];

export const pricedProducts: PricedProduct[] = [];
