-- Dairy, eggs, and dietary/certification variants for canonical product classes.
-- Depends on produce_classes(id,parent_id,segment,label,depth,sort_order).
insert into produce_classes (id, parent_id, segment, label, depth, sort_order) values
  ('dairy', null, 'dairy', 'Dairy and eggs', 0, 100),
  ('dairy-milk', 'dairy', 'dairy', 'Milk', 1, 10),
  ('milk-skim-0-fat', 'dairy-milk', 'dairy', 'Skim milk 0%', 2, 10),
  ('milk-light-05-fat', 'dairy-milk', 'dairy', 'Light milk 0.5%', 2, 20),
  ('milk-low-fat-15', 'dairy-milk', 'dairy', 'Low-fat milk 1.5%', 2, 30),
  ('milk-whole-30', 'dairy-milk', 'dairy', 'Whole milk 3.0%', 2, 40),
  ('milk-extra-rich-35', 'dairy-milk', 'dairy', 'Extra rich milk 3.5%', 2, 50),
  ('dairy-filmjolk', 'dairy', 'dairy', 'Filmjölk', 1, 20),
  ('dairy-yogurt', 'dairy', 'dairy', 'Yogurt', 1, 30),
  ('yogurt-plain', 'dairy-yogurt', 'dairy', 'Plain yogurt', 2, 10),
  ('yogurt-flavored', 'dairy-yogurt', 'dairy', 'Flavored yogurt', 2, 20),
  ('dairy-creme-fraiche', 'dairy', 'dairy', 'Crème fraîche', 1, 40),
  ('dairy-sour-cream', 'dairy', 'dairy', 'Sour cream', 1, 50),
  ('dairy-cottage-cheese', 'dairy', 'dairy', 'Cottage cheese', 1, 60),
  ('dairy-cream-cheese', 'dairy', 'dairy', 'Cream cheese', 1, 70),
  ('dairy-butter', 'dairy', 'dairy', 'Butter', 1, 80),
  ('butter-salted', 'dairy-butter', 'dairy', 'Salted butter', 2, 10),
  ('butter-unsalted', 'dairy-butter', 'dairy', 'Unsalted butter', 2, 20),
  ('dairy-hard-cheese', 'dairy', 'dairy', 'Hard cheese', 1, 90),
  ('hard-cheese-lagrad', 'dairy-hard-cheese', 'dairy', 'Lagrad hard cheese', 2, 10),
  ('hard-cheese-herrgard', 'dairy-hard-cheese', 'dairy', 'Herrgård cheese', 2, 20),
  ('hard-cheese-greve', 'dairy-hard-cheese', 'dairy', 'Grevé cheese', 2, 30),
  ('hard-cheese-prast', 'dairy-hard-cheese', 'dairy', 'Präst cheese', 2, 40),
  ('dairy-fresh-cheese', 'dairy', 'dairy', 'Fresh cheese', 1, 100),
  ('fresh-cheese-mozzarella', 'dairy-fresh-cheese', 'dairy', 'Mozzarella', 2, 10),
  ('fresh-cheese-feta', 'dairy-fresh-cheese', 'dairy', 'Feta', 2, 20),
  ('eggs', 'dairy', 'dairy', 'Eggs', 1, 110),
  ('eggs-counted-6', 'eggs', 'dairy', 'Eggs 6-pack', 2, 10),
  ('eggs-counted-10', 'eggs', 'dairy', 'Eggs 10-pack', 2, 20),
  ('eggs-counted-12', 'eggs', 'dairy', 'Eggs 12-pack', 2, 30),
  ('eggs-size-s', 'eggs', 'dairy', 'Eggs size S', 2, 40),
  ('eggs-size-m', 'eggs', 'dairy', 'Eggs size M', 2, 50),
  ('eggs-size-l', 'eggs', 'dairy', 'Eggs size L', 2, 60),
  ('variant-lactose-free', 'dairy', 'dairy_variant', 'Lactose-free variant', 1, 200),
  ('variant-krav-organic', 'dairy', 'dairy_variant', 'KRAV organic variant', 1, 210),
  ('variant-eu-organic', 'dairy', 'dairy_variant', 'EU-organic variant', 1, 220)
on conflict (id) do update set
  parent_id = excluded.parent_id,
  segment = excluded.segment,
  label = excluded.label,
  depth = excluded.depth,
  sort_order = excluded.sort_order,
  updated_at = now();
