-- Produce taxonomy seed for GroceryView canonical product classes.
-- Depends on produce_classes(id,parent_id,segment,label,depth,sort_order).
-- Depth 0 entries are the operator-facing top-level produce families; child
-- rows capture species and high-signal retail varieties used by matchers.
insert into produce_classes (id, parent_id, segment, label, depth, sort_order) values
  ('vegetable-root', null, 'produce', 'Root vegetables', 0, 10),
  ('vegetable-leaf', null, 'produce', 'Leaf vegetables', 0, 20),
  ('vegetable-fruit', null, 'produce', 'Fruit vegetables', 0, 30),
  ('vegetable-cruciferous', null, 'produce', 'Cruciferous vegetables', 0, 40),
  ('vegetable-bulb', null, 'produce', 'Bulb and stem vegetables', 0, 50),
  ('vegetable-allium', null, 'produce', 'Alliums', 0, 60),
  ('fruit-pome', null, 'produce', 'Pome fruit', 0, 70),
  ('fruit-stone', null, 'produce', 'Stone fruit', 0, 80),
  ('fruit-berry', null, 'produce', 'Berries and grapes', 0, 90),
  ('fruit-citrus', null, 'produce', 'Citrus fruit', 0, 100),
  ('fruit-tropical', null, 'produce', 'Tropical fruit', 0, 110),
  ('herb-leaf', null, 'produce', 'Leaf herbs', 0, 120),
  ('herb-root', null, 'produce', 'Root and rhizome herbs', 0, 130),
  ('mushroom', null, 'produce', 'Mushrooms', 0, 140),

  ('carrot', 'vegetable-root', 'produce', 'Carrot', 1, 10),
  ('beetroot', 'vegetable-root', 'produce', 'Beetroot', 1, 20),
  ('parsnip', 'vegetable-root', 'produce', 'Parsnip', 1, 30),
  ('celeriac', 'vegetable-root', 'produce', 'Celeriac', 1, 40),
  ('radish', 'vegetable-root', 'produce', 'Radish', 1, 50),
  ('rutabaga', 'vegetable-root', 'produce', 'Rutabaga', 1, 60),
  ('turnip', 'vegetable-root', 'produce', 'Turnip', 1, 70),
  ('potato', 'vegetable-root', 'produce', 'Potato', 1, 80),
  ('potato-floury', 'potato', 'produce', 'Floury potato', 2, 10),
  ('potato-king-edward', 'potato-floury', 'produce', 'King Edward potato', 3, 10),
  ('potato-bintje', 'potato-floury', 'produce', 'Bintje potato', 3, 20),
  ('potato-waxy', 'potato', 'produce', 'Waxy potato', 2, 20),
  ('potato-cara', 'potato-waxy', 'produce', 'Cara potato', 3, 10),
  ('potato-mandel', 'potato-waxy', 'produce', 'Mandel potato', 3, 20),
  ('potato-charlotte', 'potato-waxy', 'produce', 'Charlotte potato', 3, 30),
  ('potato-new', 'potato', 'produce', 'New potato', 2, 30),

  ('lettuce', 'vegetable-leaf', 'produce', 'Lettuce', 1, 10),
  ('spinach', 'vegetable-leaf', 'produce', 'Spinach', 1, 20),
  ('kale', 'vegetable-leaf', 'produce', 'Kale', 1, 30),
  ('chard', 'vegetable-leaf', 'produce', 'Chard', 1, 40),
  ('arugula', 'vegetable-leaf', 'produce', 'Arugula', 1, 50),
  ('pak-choi', 'vegetable-leaf', 'produce', 'Pak choi', 1, 60),
  ('mixed-salad', 'vegetable-leaf', 'produce', 'Mixed salad leaves', 1, 70),

  ('tomato', 'vegetable-fruit', 'produce', 'Tomato', 1, 10),
  ('tomato-cherry', 'tomato', 'produce', 'Cherry tomato', 2, 10),
  ('tomato-vine', 'tomato', 'produce', 'Vine tomato', 2, 20),
  ('tomato-plum', 'tomato', 'produce', 'Plum tomato', 2, 30),
  ('tomato-beef', 'tomato', 'produce', 'Beef tomato', 2, 40),
  ('tomato-round', 'tomato', 'produce', 'Round tomato', 2, 50),
  ('cucumber', 'vegetable-fruit', 'produce', 'Cucumber', 1, 20),
  ('pepper', 'vegetable-fruit', 'produce', 'Sweet pepper', 1, 30),
  ('zucchini', 'vegetable-fruit', 'produce', 'Zucchini', 1, 40),
  ('aubergine', 'vegetable-fruit', 'produce', 'Aubergine', 1, 50),
  ('pumpkin', 'vegetable-fruit', 'produce', 'Pumpkin and squash', 1, 60),

  ('broccoli', 'vegetable-cruciferous', 'produce', 'Broccoli', 1, 10),
  ('cauliflower', 'vegetable-cruciferous', 'produce', 'Cauliflower', 1, 20),
  ('white-cabbage', 'vegetable-cruciferous', 'produce', 'White cabbage', 1, 30),
  ('red-cabbage', 'vegetable-cruciferous', 'produce', 'Red cabbage', 1, 40),
  ('savoy-cabbage', 'vegetable-cruciferous', 'produce', 'Savoy cabbage', 1, 50),
  ('brussels-sprout', 'vegetable-cruciferous', 'produce', 'Brussels sprout', 1, 60),
  ('kohlrabi', 'vegetable-cruciferous', 'produce', 'Kohlrabi', 1, 70),

  ('fennel-bulb', 'vegetable-bulb', 'produce', 'Fennel bulb', 1, 10),
  ('celery-stalk', 'vegetable-bulb', 'produce', 'Celery stalk', 1, 20),
  ('asparagus', 'vegetable-bulb', 'produce', 'Asparagus', 1, 30),
  ('artichoke', 'vegetable-bulb', 'produce', 'Artichoke', 1, 40),

  ('yellow-onion', 'vegetable-allium', 'produce', 'Yellow onion', 1, 10),
  ('red-onion', 'vegetable-allium', 'produce', 'Red onion', 1, 20),
  ('shallot', 'vegetable-allium', 'produce', 'Shallot', 1, 30),
  ('garlic', 'vegetable-allium', 'produce', 'Garlic', 1, 40),
  ('spring-onion', 'vegetable-allium', 'produce', 'Spring onion', 1, 50),
  ('leek', 'vegetable-allium', 'produce', 'Leek', 1, 60),

  ('apple', 'fruit-pome', 'produce', 'Apple', 1, 10),
  ('apple-granny-smith', 'apple', 'produce', 'Granny Smith apple', 2, 10),
  ('apple-pink-lady', 'apple', 'produce', 'Pink Lady apple', 2, 20),
  ('apple-royal-gala', 'apple', 'produce', 'Royal Gala apple', 2, 30),
  ('apple-gala', 'apple', 'produce', 'Gala apple', 2, 40),
  ('apple-golden-delicious', 'apple', 'produce', 'Golden Delicious apple', 2, 50),
  ('apple-red-delicious', 'apple', 'produce', 'Red Delicious apple', 2, 60),
  ('apple-jazz', 'apple', 'produce', 'Jazz apple', 2, 70),
  ('apple-kanzi', 'apple', 'produce', 'Kanzi apple', 2, 80),
  ('apple-ingrid-marie', 'apple', 'produce', 'Ingrid Marie apple', 2, 90),
  ('pear', 'fruit-pome', 'produce', 'Pear', 1, 20),
  ('pear-conference', 'pear', 'produce', 'Conference pear', 2, 10),
  ('pear-anjou', 'pear', 'produce', 'Anjou pear', 2, 20),
  ('pear-williams', 'pear', 'produce', 'Williams pear', 2, 30),

  ('peach', 'fruit-stone', 'produce', 'Peach', 1, 10),
  ('nectarine', 'fruit-stone', 'produce', 'Nectarine', 1, 20),
  ('plum', 'fruit-stone', 'produce', 'Plum', 1, 30),
  ('apricot', 'fruit-stone', 'produce', 'Apricot', 1, 40),
  ('cherry', 'fruit-stone', 'produce', 'Cherry', 1, 50),

  ('strawberry', 'fruit-berry', 'produce', 'Strawberry', 1, 10),
  ('blueberry', 'fruit-berry', 'produce', 'Blueberry', 1, 20),
  ('raspberry', 'fruit-berry', 'produce', 'Raspberry', 1, 30),
  ('blackberry', 'fruit-berry', 'produce', 'Blackberry', 1, 40),
  ('grape', 'fruit-berry', 'produce', 'Grape', 1, 50),
  ('redcurrant', 'fruit-berry', 'produce', 'Redcurrant', 1, 60),

  ('orange', 'fruit-citrus', 'produce', 'Orange', 1, 10),
  ('blood-orange', 'fruit-citrus', 'produce', 'Blood orange', 1, 20),
  ('lemon', 'fruit-citrus', 'produce', 'Lemon', 1, 30),
  ('lime', 'fruit-citrus', 'produce', 'Lime', 1, 40),
  ('grapefruit', 'fruit-citrus', 'produce', 'Grapefruit', 1, 50),
  ('clementine', 'fruit-citrus', 'produce', 'Clementine and mandarin', 1, 60),
  ('pomelo', 'fruit-citrus', 'produce', 'Pomelo', 1, 70),

  ('banana', 'fruit-tropical', 'produce', 'Banana', 1, 10),
  ('avocado', 'fruit-tropical', 'produce', 'Avocado', 1, 20),
  ('mango', 'fruit-tropical', 'produce', 'Mango', 1, 30),
  ('pineapple', 'fruit-tropical', 'produce', 'Pineapple', 1, 40),
  ('kiwi', 'fruit-tropical', 'produce', 'Kiwi', 1, 50),
  ('melon', 'fruit-tropical', 'produce', 'Melon', 1, 60),
  ('papaya', 'fruit-tropical', 'produce', 'Papaya', 1, 70),
  ('passionfruit', 'fruit-tropical', 'produce', 'Passionfruit', 1, 80),

  ('basil', 'herb-leaf', 'produce', 'Basil', 1, 10),
  ('coriander', 'herb-leaf', 'produce', 'Coriander', 1, 20),
  ('parsley', 'herb-leaf', 'produce', 'Parsley', 1, 30),
  ('dill', 'herb-leaf', 'produce', 'Dill', 1, 40),
  ('mint', 'herb-leaf', 'produce', 'Mint', 1, 50),
  ('chives', 'herb-leaf', 'produce', 'Chives', 1, 60),
  ('thyme', 'herb-leaf', 'produce', 'Thyme', 1, 70),
  ('rosemary', 'herb-leaf', 'produce', 'Rosemary', 1, 80),
  ('oregano', 'herb-leaf', 'produce', 'Oregano', 1, 90),

  ('ginger', 'herb-root', 'produce', 'Ginger', 1, 10),
  ('turmeric', 'herb-root', 'produce', 'Turmeric', 1, 20),
  ('horseradish', 'herb-root', 'produce', 'Horseradish', 1, 30),
  ('galangal', 'herb-root', 'produce', 'Galangal', 1, 40),

  ('mushroom-white-button', 'mushroom', 'produce', 'White button mushroom', 1, 10),
  ('mushroom-brown-chestnut', 'mushroom', 'produce', 'Brown chestnut mushroom', 1, 20),
  ('mushroom-portobello', 'mushroom', 'produce', 'Portobello mushroom', 1, 30),
  ('mushroom-oyster', 'mushroom', 'produce', 'Oyster mushroom', 1, 40),
  ('mushroom-king-oyster', 'mushroom', 'produce', 'King oyster mushroom', 1, 50),
  ('mushroom-shiitake', 'mushroom', 'produce', 'Shiitake mushroom', 1, 60),
  ('mushroom-chanterelle', 'mushroom', 'produce', 'Chanterelle mushroom', 1, 70),
  ('mushroom-porcini-boletus', 'mushroom', 'produce', 'Porcini and boletus mushroom', 1, 80),
  ('mushroom-enoki', 'mushroom', 'produce', 'Enoki mushroom', 1, 90),
  ('mushroom-mixed-pack', 'mushroom', 'produce', 'Mixed mushroom pack', 1, 100),
  ('mushroom-generic-unknown', 'mushroom', 'produce', 'Generic edible mushroom', 1, 110)
on conflict (id) do update set
  parent_id = excluded.parent_id,
  segment = excluded.segment,
  label = excluded.label,
  depth = excluded.depth,
  sort_order = excluded.sort_order,
  updated_at = now();
