-- Produce product class taxonomy seed.
-- The seed is idempotent and keeps parent classes before child classes.

create table if not exists produce_classes (
  id text primary key,
  parent_id text references produce_classes(id) on delete restrict,
  name text not null,
  segment text not null check (segment in ('vegetable', 'fruit', 'herb', 'mushroom')),
  depth integer not null check (depth between 0 and 3),
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produce_classes_parent_idx on produce_classes(parent_id);
create index if not exists produce_classes_segment_idx on produce_classes(segment);

insert into produce_classes(id, parent_id, name, segment, depth, sort_order) values
  ('vegetable-root', null, 'Root vegetables', 'vegetable', 0, 100),
  ('vegetable-leaf', null, 'Leaf vegetables', 'vegetable', 0, 200),
  ('vegetable-fruit', null, 'Fruit vegetables', 'vegetable', 0, 300),
  ('vegetable-cruciferous', null, 'Cruciferous vegetables', 'vegetable', 0, 400),
  ('vegetable-bulb', null, 'Bulb vegetables', 'vegetable', 0, 500),
  ('vegetable-allium', null, 'Alliums', 'vegetable', 0, 600),
  ('fruit-pome', null, 'Pome fruit', 'fruit', 0, 700),
  ('fruit-stone', null, 'Stone fruit', 'fruit', 0, 800),
  ('fruit-berry', null, 'Berries', 'fruit', 0, 900),
  ('fruit-citrus', null, 'Citrus fruit', 'fruit', 0, 1000),
  ('fruit-tropical', null, 'Tropical fruit', 'fruit', 0, 1100),
  ('herb-leaf', null, 'Leaf herbs', 'herb', 0, 1200),
  ('herb-root', null, 'Root herbs', 'herb', 0, 1300),
  ('mushroom', null, 'Mushrooms', 'mushroom', 0, 1400),

  ('vegetable-root/carrot', 'vegetable-root', 'Carrot', 'vegetable', 1, 101),
  ('vegetable-root/parsnip', 'vegetable-root', 'Parsnip', 'vegetable', 1, 102),
  ('vegetable-root/beetroot', 'vegetable-root', 'Beetroot', 'vegetable', 1, 103),
  ('vegetable-root/celeriac', 'vegetable-root', 'Celeriac', 'vegetable', 1, 104),
  ('vegetable-root/rutabaga', 'vegetable-root', 'Rutabaga', 'vegetable', 1, 105),
  ('vegetable-root/turnip', 'vegetable-root', 'Turnip', 'vegetable', 1, 106),
  ('vegetable-root/radish', 'vegetable-root', 'Radish', 'vegetable', 1, 107),
  ('vegetable-root/sweet-potato', 'vegetable-root', 'Sweet potato', 'vegetable', 1, 108),
  ('vegetable-root/potato', 'vegetable-root', 'Potato', 'vegetable', 1, 109),
  ('vegetable-root/potato/floury', 'vegetable-root/potato', 'Floury potato', 'vegetable', 2, 110),
  ('vegetable-root/potato/floury/king-edward', 'vegetable-root/potato/floury', 'King Edward potato', 'vegetable', 3, 111),
  ('vegetable-root/potato/floury/bintje', 'vegetable-root/potato/floury', 'Bintje potato', 'vegetable', 3, 112),
  ('vegetable-root/potato/waxy', 'vegetable-root/potato', 'Waxy potato', 'vegetable', 2, 113),
  ('vegetable-root/potato/waxy/cara', 'vegetable-root/potato/waxy', 'Cara potato', 'vegetable', 3, 114),
  ('vegetable-root/potato/waxy/mandel', 'vegetable-root/potato/waxy', 'Mandel potato', 'vegetable', 3, 115),
  ('vegetable-root/potato/waxy/charlotte', 'vegetable-root/potato/waxy', 'Charlotte potato', 'vegetable', 3, 116),
  ('vegetable-root/potato/new-potato', 'vegetable-root/potato', 'New potato', 'vegetable', 2, 117),

  ('vegetable-leaf/lettuce', 'vegetable-leaf', 'Lettuce', 'vegetable', 1, 201),
  ('vegetable-leaf/spinach', 'vegetable-leaf', 'Spinach', 'vegetable', 1, 202),
  ('vegetable-leaf/kale', 'vegetable-leaf', 'Kale', 'vegetable', 1, 203),
  ('vegetable-leaf/chard', 'vegetable-leaf', 'Chard', 'vegetable', 1, 204),
  ('vegetable-leaf/rocket', 'vegetable-leaf', 'Rocket', 'vegetable', 1, 205),
  ('vegetable-leaf/pak-choi', 'vegetable-leaf', 'Pak choi', 'vegetable', 1, 206),
  ('vegetable-leaf/endive', 'vegetable-leaf', 'Endive', 'vegetable', 1, 207),
  ('vegetable-leaf/watercress', 'vegetable-leaf', 'Watercress', 'vegetable', 1, 208),

  ('vegetable-fruit/tomato', 'vegetable-fruit', 'Tomato', 'vegetable', 1, 301),
  ('vegetable-fruit/tomato/cherry', 'vegetable-fruit/tomato', 'Cherry tomato', 'vegetable', 2, 302),
  ('vegetable-fruit/tomato/vine', 'vegetable-fruit/tomato', 'Vine tomato', 'vegetable', 2, 303),
  ('vegetable-fruit/tomato/plum', 'vegetable-fruit/tomato', 'Plum tomato', 'vegetable', 2, 304),
  ('vegetable-fruit/tomato/beef', 'vegetable-fruit/tomato', 'Beef tomato', 'vegetable', 2, 305),
  ('vegetable-fruit/tomato/round', 'vegetable-fruit/tomato', 'Round tomato', 'vegetable', 2, 306),
  ('vegetable-fruit/cucumber', 'vegetable-fruit', 'Cucumber', 'vegetable', 1, 307),
  ('vegetable-fruit/pepper', 'vegetable-fruit', 'Pepper', 'vegetable', 1, 308),
  ('vegetable-fruit/aubergine', 'vegetable-fruit', 'Aubergine', 'vegetable', 1, 309),
  ('vegetable-fruit/courgette', 'vegetable-fruit', 'Courgette', 'vegetable', 1, 310),
  ('vegetable-fruit/pumpkin', 'vegetable-fruit', 'Pumpkin', 'vegetable', 1, 311),
  ('vegetable-fruit/squash', 'vegetable-fruit', 'Squash', 'vegetable', 1, 312),

  ('vegetable-cruciferous/broccoli', 'vegetable-cruciferous', 'Broccoli', 'vegetable', 1, 401),
  ('vegetable-cruciferous/cauliflower', 'vegetable-cruciferous', 'Cauliflower', 'vegetable', 1, 402),
  ('vegetable-cruciferous/white-cabbage', 'vegetable-cruciferous', 'White cabbage', 'vegetable', 1, 403),
  ('vegetable-cruciferous/red-cabbage', 'vegetable-cruciferous', 'Red cabbage', 'vegetable', 1, 404),
  ('vegetable-cruciferous/savoy-cabbage', 'vegetable-cruciferous', 'Savoy cabbage', 'vegetable', 1, 405),
  ('vegetable-cruciferous/brussels-sprouts', 'vegetable-cruciferous', 'Brussels sprouts', 'vegetable', 1, 406),
  ('vegetable-cruciferous/romanesco', 'vegetable-cruciferous', 'Romanesco', 'vegetable', 1, 407),
  ('vegetable-cruciferous/kohlrabi', 'vegetable-cruciferous', 'Kohlrabi', 'vegetable', 1, 408),

  ('vegetable-bulb/fennel', 'vegetable-bulb', 'Fennel', 'vegetable', 1, 501),
  ('vegetable-bulb/celery', 'vegetable-bulb', 'Celery', 'vegetable', 1, 502),
  ('vegetable-bulb/artichoke', 'vegetable-bulb', 'Artichoke', 'vegetable', 1, 503),
  ('vegetable-bulb/asparagus', 'vegetable-bulb', 'Asparagus', 'vegetable', 1, 504),
  ('vegetable-bulb/rhubarb', 'vegetable-bulb', 'Rhubarb', 'vegetable', 1, 505),

  ('vegetable-allium/yellow-onion', 'vegetable-allium', 'Yellow onion', 'vegetable', 1, 601),
  ('vegetable-allium/red-onion', 'vegetable-allium', 'Red onion', 'vegetable', 1, 602),
  ('vegetable-allium/shallot', 'vegetable-allium', 'Shallot', 'vegetable', 1, 603),
  ('vegetable-allium/garlic', 'vegetable-allium', 'Garlic', 'vegetable', 1, 604),
  ('vegetable-allium/leek', 'vegetable-allium', 'Leek', 'vegetable', 1, 605),
  ('vegetable-allium/spring-onion', 'vegetable-allium', 'Spring onion', 'vegetable', 1, 606),
  ('vegetable-allium/chives', 'vegetable-allium', 'Chives', 'vegetable', 1, 607),

  ('fruit-pome/apple', 'fruit-pome', 'Apple', 'fruit', 1, 701),
  ('fruit-pome/apple/granny-smith', 'fruit-pome/apple', 'Granny Smith apple', 'fruit', 2, 702),
  ('fruit-pome/apple/pink-lady', 'fruit-pome/apple', 'Pink Lady apple', 'fruit', 2, 703),
  ('fruit-pome/apple/royal-gala', 'fruit-pome/apple', 'Royal Gala apple', 'fruit', 2, 704),
  ('fruit-pome/apple/golden-delicious', 'fruit-pome/apple', 'Golden Delicious apple', 'fruit', 2, 705),
  ('fruit-pome/apple/red-delicious', 'fruit-pome/apple', 'Red Delicious apple', 'fruit', 2, 706),
  ('fruit-pome/apple/jazz', 'fruit-pome/apple', 'Jazz apple', 'fruit', 2, 707),
  ('fruit-pome/apple/braeburn', 'fruit-pome/apple', 'Braeburn apple', 'fruit', 2, 708),
  ('fruit-pome/apple/ingrid-marie', 'fruit-pome/apple', 'Ingrid Marie apple', 'fruit', 2, 709),
  ('fruit-pome/pear', 'fruit-pome', 'Pear', 'fruit', 1, 710),
  ('fruit-pome/quince', 'fruit-pome', 'Quince', 'fruit', 1, 711),

  ('fruit-stone/peach', 'fruit-stone', 'Peach', 'fruit', 1, 801),
  ('fruit-stone/nectarine', 'fruit-stone', 'Nectarine', 'fruit', 1, 802),
  ('fruit-stone/plum', 'fruit-stone', 'Plum', 'fruit', 1, 803),
  ('fruit-stone/apricot', 'fruit-stone', 'Apricot', 'fruit', 1, 804),
  ('fruit-stone/cherry', 'fruit-stone', 'Cherry', 'fruit', 1, 805),
  ('fruit-stone/mango', 'fruit-stone', 'Mango', 'fruit', 1, 806),

  ('fruit-berry/strawberry', 'fruit-berry', 'Strawberry', 'fruit', 1, 901),
  ('fruit-berry/raspberry', 'fruit-berry', 'Raspberry', 'fruit', 1, 902),
  ('fruit-berry/blueberry', 'fruit-berry', 'Blueberry', 'fruit', 1, 903),
  ('fruit-berry/blackberry', 'fruit-berry', 'Blackberry', 'fruit', 1, 904),
  ('fruit-berry/redcurrant', 'fruit-berry', 'Redcurrant', 'fruit', 1, 905),
  ('fruit-berry/blackcurrant', 'fruit-berry', 'Blackcurrant', 'fruit', 1, 906),
  ('fruit-berry/gooseberry', 'fruit-berry', 'Gooseberry', 'fruit', 1, 907),
  ('fruit-berry/grape', 'fruit-berry', 'Grape', 'fruit', 1, 908),

  ('fruit-citrus/orange', 'fruit-citrus', 'Orange', 'fruit', 1, 1001),
  ('fruit-citrus/clementine', 'fruit-citrus', 'Clementine', 'fruit', 1, 1002),
  ('fruit-citrus/satsuma', 'fruit-citrus', 'Satsuma', 'fruit', 1, 1003),
  ('fruit-citrus/mandarin', 'fruit-citrus', 'Mandarin', 'fruit', 1, 1004),
  ('fruit-citrus/lemon', 'fruit-citrus', 'Lemon', 'fruit', 1, 1005),
  ('fruit-citrus/lime', 'fruit-citrus', 'Lime', 'fruit', 1, 1006),
  ('fruit-citrus/grapefruit', 'fruit-citrus', 'Grapefruit', 'fruit', 1, 1007),
  ('fruit-citrus/blood-orange', 'fruit-citrus', 'Blood orange', 'fruit', 1, 1008),

  ('fruit-tropical/banana', 'fruit-tropical', 'Banana', 'fruit', 1, 1101),
  ('fruit-tropical/pineapple', 'fruit-tropical', 'Pineapple', 'fruit', 1, 1102),
  ('fruit-tropical/kiwi', 'fruit-tropical', 'Kiwi', 'fruit', 1, 1103),
  ('fruit-tropical/passion-fruit', 'fruit-tropical', 'Passion fruit', 'fruit', 1, 1104),
  ('fruit-tropical/papaya', 'fruit-tropical', 'Papaya', 'fruit', 1, 1105),
  ('fruit-tropical/dragon-fruit', 'fruit-tropical', 'Dragon fruit', 'fruit', 1, 1106),
  ('fruit-tropical/coconut', 'fruit-tropical', 'Coconut', 'fruit', 1, 1107),
  ('fruit-tropical/pomegranate', 'fruit-tropical', 'Pomegranate', 'fruit', 1, 1108),
  ('fruit-tropical/melon', 'fruit-tropical', 'Melon', 'fruit', 1, 1109),

  ('herb-leaf/basil', 'herb-leaf', 'Basil', 'herb', 1, 1201),
  ('herb-leaf/parsley', 'herb-leaf', 'Parsley', 'herb', 1, 1202),
  ('herb-leaf/coriander', 'herb-leaf', 'Coriander', 'herb', 1, 1203),
  ('herb-leaf/dill', 'herb-leaf', 'Dill', 'herb', 1, 1204),
  ('herb-leaf/mint', 'herb-leaf', 'Mint', 'herb', 1, 1205),
  ('herb-leaf/thyme', 'herb-leaf', 'Thyme', 'herb', 1, 1206),
  ('herb-leaf/rosemary', 'herb-leaf', 'Rosemary', 'herb', 1, 1207),
  ('herb-leaf/sage', 'herb-leaf', 'Sage', 'herb', 1, 1208),
  ('herb-leaf/oregano', 'herb-leaf', 'Oregano', 'herb', 1, 1209),

  ('herb-root/ginger', 'herb-root', 'Ginger', 'herb', 1, 1301),
  ('herb-root/turmeric', 'herb-root', 'Turmeric', 'herb', 1, 1302),
  ('herb-root/galangal', 'herb-root', 'Galangal', 'herb', 1, 1303),
  ('herb-root/horseradish', 'herb-root', 'Horseradish', 'herb', 1, 1304),

  ('mushroom/champignon', 'mushroom', 'Champignon', 'mushroom', 1, 1401),
  ('mushroom/portobello', 'mushroom', 'Portobello', 'mushroom', 1, 1402),
  ('mushroom/shiitake', 'mushroom', 'Shiitake', 'mushroom', 1, 1403),
  ('mushroom/oyster', 'mushroom', 'Oyster mushroom', 'mushroom', 1, 1404),
  ('mushroom/chanterelle', 'mushroom', 'Chanterelle', 'mushroom', 1, 1405),
  ('mushroom/porcini', 'mushroom', 'Porcini', 'mushroom', 1, 1406)
on conflict (id) do update set
  parent_id = excluded.parent_id,
  name = excluded.name,
  segment = excluded.segment,
  depth = excluded.depth,
  sort_order = excluded.sort_order,
  updated_at = now();
