-- Canonical fresh-produce class taxonomy for vegetables, fruits, herbs, and mushrooms.
-- Depends on produce_classes(id,parent_id,segment,label,depth,sort_order).
insert into produce_classes (id, parent_id, segment, label, depth, sort_order) values
  ('vegetable-root', null, 'produce', 'Root vegetables', 0, 10),
  ('vegetable-leaf', null, 'produce', 'Leaf vegetables', 0, 20),
  ('vegetable-fruit', null, 'produce', 'Fruit vegetables', 0, 30),
  ('vegetable-cruciferous', null, 'produce', 'Cruciferous vegetables', 0, 40),
  ('vegetable-bulb', null, 'produce', 'Bulb vegetables', 0, 50),
  ('vegetable-allium', null, 'produce', 'Alliums', 0, 60),
  ('fruit-pome', null, 'produce', 'Pome fruit', 0, 70),
  ('fruit-stone', null, 'produce', 'Stone fruit', 0, 80),
  ('fruit-berry', null, 'produce', 'Berries', 0, 90),
  ('fruit-citrus', null, 'produce', 'Citrus fruit', 0, 100),
  ('fruit-tropical', null, 'produce', 'Tropical fruit', 0, 110),
  ('herb-leaf', null, 'produce', 'Leaf herbs', 0, 120),
  ('herb-root', null, 'produce', 'Root herbs', 0, 130),
  ('mushroom', null, 'produce', 'Mushrooms', 0, 140),

  ('potatoes', 'vegetable-root', 'produce', 'Potatoes', 1, 10),
  ('potato-floury', 'potatoes', 'produce', 'Floury potatoes', 2, 10),
  ('potato-king-edward', 'potato-floury', 'produce', 'King Edward potatoes', 3, 10),
  ('potato-bintje', 'potato-floury', 'produce', 'Bintje potatoes', 3, 20),
  ('potato-waxy', 'potatoes', 'produce', 'Waxy potatoes', 2, 20),
  ('potato-cara', 'potato-waxy', 'produce', 'Cara potatoes', 3, 10),
  ('potato-mandel', 'potato-waxy', 'produce', 'Mandel potatoes', 3, 20),
  ('potato-charlotte', 'potato-waxy', 'produce', 'Charlotte potatoes', 3, 30),
  ('potato-new', 'potatoes', 'produce', 'New potatoes', 2, 30),
  ('carrots', 'vegetable-root', 'produce', 'Carrots', 1, 20),
  ('carrot-orange', 'carrots', 'produce', 'Orange carrots', 2, 10),
  ('carrot-rainbow', 'carrots', 'produce', 'Rainbow carrots', 2, 20),
  ('beetroot', 'vegetable-root', 'produce', 'Beetroot', 1, 30),
  ('parsnip', 'vegetable-root', 'produce', 'Parsnip', 1, 40),
  ('celeriac', 'vegetable-root', 'produce', 'Celeriac', 1, 50),
  ('turnip', 'vegetable-root', 'produce', 'Turnip', 1, 60),
  ('swede-rutabaga', 'vegetable-root', 'produce', 'Swede and rutabaga', 1, 70),
  ('radish', 'vegetable-root', 'produce', 'Radish', 1, 80),

  ('leafy-vegetables', 'vegetable-leaf', 'produce', 'Leafy vegetables', 1, 10),
  ('lettuce', 'leafy-vegetables', 'produce', 'Lettuce', 2, 10),
  ('lettuce-iceberg', 'lettuce', 'produce', 'Iceberg lettuce', 3, 10),
  ('lettuce-romaine', 'lettuce', 'produce', 'Romaine lettuce', 3, 20),
  ('lettuce-butterhead', 'lettuce', 'produce', 'Butterhead lettuce', 3, 30),
  ('lettuce-baby-leaf', 'lettuce', 'produce', 'Baby leaf lettuce', 3, 40),
  ('spinach', 'leafy-vegetables', 'produce', 'Spinach', 2, 20),
  ('rocket-arugula', 'leafy-vegetables', 'produce', 'Rocket and arugula', 2, 30),
  ('kale', 'leafy-vegetables', 'produce', 'Kale', 2, 40),
  ('chard', 'leafy-vegetables', 'produce', 'Chard', 2, 50),
  ('pak-choi', 'leafy-vegetables', 'produce', 'Pak choi', 2, 60),
  ('cabbage-leaf', 'leafy-vegetables', 'produce', 'Leaf cabbage', 2, 70),

  ('tomatoes', 'vegetable-fruit', 'produce', 'Tomatoes', 1, 10),
  ('tomato-cherry', 'tomatoes', 'produce', 'Cherry tomatoes', 2, 10),
  ('tomato-vine', 'tomatoes', 'produce', 'Vine tomatoes', 2, 20),
  ('tomato-plum', 'tomatoes', 'produce', 'Plum tomatoes', 2, 30),
  ('tomato-beef', 'tomatoes', 'produce', 'Beef tomatoes', 2, 40),
  ('tomato-round', 'tomatoes', 'produce', 'Round tomatoes', 2, 50),
  ('tomato-cocktail', 'tomatoes', 'produce', 'Cocktail tomatoes', 2, 60),
  ('tomato-snack-mini', 'tomatoes', 'produce', 'Snack and mini tomatoes', 2, 70),
  ('tomato-mixed-pack', 'tomatoes', 'produce', 'Mixed tomato packs', 2, 80),
  ('cucumber', 'vegetable-fruit', 'produce', 'Cucumber', 1, 20),
  ('pepper', 'vegetable-fruit', 'produce', 'Sweet peppers', 1, 30),
  ('pepper-red', 'pepper', 'produce', 'Red peppers', 2, 10),
  ('pepper-yellow', 'pepper', 'produce', 'Yellow peppers', 2, 20),
  ('pepper-green', 'pepper', 'produce', 'Green peppers', 2, 30),
  ('courgette-zucchini', 'vegetable-fruit', 'produce', 'Courgette and zucchini', 1, 40),
  ('aubergine-eggplant', 'vegetable-fruit', 'produce', 'Aubergine and eggplant', 1, 50),
  ('squash-pumpkin', 'vegetable-fruit', 'produce', 'Squash and pumpkin', 1, 60),
  ('avocado', 'vegetable-fruit', 'produce', 'Avocado', 1, 70),

  ('broccoli', 'vegetable-cruciferous', 'produce', 'Broccoli', 1, 10),
  ('cauliflower', 'vegetable-cruciferous', 'produce', 'Cauliflower', 1, 20),
  ('cabbage', 'vegetable-cruciferous', 'produce', 'Cabbage', 1, 30),
  ('cabbage-white', 'cabbage', 'produce', 'White cabbage', 2, 10),
  ('cabbage-red', 'cabbage', 'produce', 'Red cabbage', 2, 20),
  ('cabbage-savoy', 'cabbage', 'produce', 'Savoy cabbage', 2, 30),
  ('brussels-sprouts', 'vegetable-cruciferous', 'produce', 'Brussels sprouts', 1, 40),
  ('kohlrabi', 'vegetable-cruciferous', 'produce', 'Kohlrabi', 1, 50),

  ('fennel-bulb', 'vegetable-bulb', 'produce', 'Fennel bulb', 1, 10),
  ('celery-bulb', 'vegetable-bulb', 'produce', 'Celery bulb', 1, 20),
  ('artichoke', 'vegetable-bulb', 'produce', 'Artichoke', 1, 30),
  ('asparagus', 'vegetable-bulb', 'produce', 'Asparagus', 1, 40),

  ('onions', 'vegetable-allium', 'produce', 'Onions', 1, 10),
  ('onion-yellow', 'onions', 'produce', 'Yellow onions', 2, 10),
  ('onion-red', 'onions', 'produce', 'Red onions', 2, 20),
  ('onion-spring', 'onions', 'produce', 'Spring onions', 2, 30),
  ('shallot', 'vegetable-allium', 'produce', 'Shallots', 1, 20),
  ('garlic', 'vegetable-allium', 'produce', 'Garlic', 1, 30),
  ('leek', 'vegetable-allium', 'produce', 'Leek', 1, 40),

  ('apples', 'fruit-pome', 'produce', 'Apples', 1, 10),
  ('apple-granny-smith', 'apples', 'produce', 'Granny Smith apples', 2, 10),
  ('apple-pink-lady', 'apples', 'produce', 'Pink Lady apples', 2, 20),
  ('apple-royal-gala', 'apples', 'produce', 'Royal Gala apples', 2, 30),
  ('apple-golden-delicious', 'apples', 'produce', 'Golden Delicious apples', 2, 40),
  ('apple-red-delicious', 'apples', 'produce', 'Red Delicious apples', 2, 50),
  ('apple-fuji', 'apples', 'produce', 'Fuji apples', 2, 60),
  ('apple-braeburn', 'apples', 'produce', 'Braeburn apples', 2, 70),
  ('apple-jazz', 'apples', 'produce', 'Jazz apples', 2, 80),
  ('apple-honeycrisp', 'apples', 'produce', 'Honeycrisp apples', 2, 90),
  ('pear', 'fruit-pome', 'produce', 'Pears', 1, 20),
  ('pear-conference', 'pear', 'produce', 'Conference pears', 2, 10),
  ('pear-comice', 'pear', 'produce', 'Comice pears', 2, 20),
  ('quince', 'fruit-pome', 'produce', 'Quince', 1, 30),

  ('peach', 'fruit-stone', 'produce', 'Peaches', 1, 10),
  ('nectarine', 'fruit-stone', 'produce', 'Nectarines', 1, 20),
  ('plum', 'fruit-stone', 'produce', 'Plums', 1, 30),
  ('apricot', 'fruit-stone', 'produce', 'Apricots', 1, 40),
  ('cherry', 'fruit-stone', 'produce', 'Cherries', 1, 50),
  ('mango', 'fruit-stone', 'produce', 'Mangoes', 1, 60),

  ('strawberry', 'fruit-berry', 'produce', 'Strawberries', 1, 10),
  ('blueberry', 'fruit-berry', 'produce', 'Blueberries', 1, 20),
  ('raspberry', 'fruit-berry', 'produce', 'Raspberries', 1, 30),
  ('blackberry', 'fruit-berry', 'produce', 'Blackberries', 1, 40),
  ('redcurrant', 'fruit-berry', 'produce', 'Redcurrants', 1, 50),
  ('blackcurrant', 'fruit-berry', 'produce', 'Blackcurrants', 1, 60),
  ('gooseberry', 'fruit-berry', 'produce', 'Gooseberries', 1, 70),
  ('grape', 'fruit-berry', 'produce', 'Grapes', 1, 80),

  ('citrus', 'fruit-citrus', 'produce', 'Citrus', 1, 10),
  ('orange', 'citrus', 'produce', 'Oranges', 2, 10),
  ('blood-orange', 'citrus', 'produce', 'Blood oranges', 2, 20),
  ('mandarin-family', 'citrus', 'produce', 'Mandarins and easy peel citrus', 2, 30),
  ('lemon', 'citrus', 'produce', 'Lemons', 2, 40),
  ('lime', 'citrus', 'produce', 'Limes', 2, 50),
  ('grapefruit', 'citrus', 'produce', 'Grapefruit', 2, 60),
  ('pomelo', 'citrus', 'produce', 'Pomelo', 2, 70),
  ('mixed-citrus', 'citrus', 'produce', 'Mixed citrus', 2, 80),

  ('banana', 'fruit-tropical', 'produce', 'Bananas', 1, 10),
  ('pineapple', 'fruit-tropical', 'produce', 'Pineapples', 1, 20),
  ('melon', 'fruit-tropical', 'produce', 'Melons', 1, 30),
  ('melon-watermelon', 'melon', 'produce', 'Watermelon', 2, 10),
  ('melon-honeydew', 'melon', 'produce', 'Honeydew melon', 2, 20),
  ('melon-cantaloupe', 'melon', 'produce', 'Cantaloupe melon', 2, 30),
  ('kiwi', 'fruit-tropical', 'produce', 'Kiwi fruit', 1, 40),
  ('passion-fruit', 'fruit-tropical', 'produce', 'Passion fruit', 1, 50),
  ('papaya', 'fruit-tropical', 'produce', 'Papaya', 1, 60),
  ('pomegranate', 'fruit-tropical', 'produce', 'Pomegranate', 1, 70),

  ('herbs', 'herb-leaf', 'produce', 'Leaf herbs', 1, 10),
  ('basil', 'herbs', 'produce', 'Basil', 2, 10),
  ('parsley', 'herbs', 'produce', 'Parsley', 2, 20),
  ('coriander-cilantro', 'herbs', 'produce', 'Coriander and cilantro', 2, 30),
  ('dill', 'herbs', 'produce', 'Dill', 2, 40),
  ('mint', 'herbs', 'produce', 'Mint', 2, 50),
  ('chives', 'herbs', 'produce', 'Chives', 2, 60),
  ('thyme', 'herbs', 'produce', 'Thyme', 2, 70),
  ('rosemary', 'herbs', 'produce', 'Rosemary', 2, 80),
  ('sage', 'herbs', 'produce', 'Sage', 2, 90),
  ('oregano', 'herbs', 'produce', 'Oregano', 2, 100),
  ('ginger', 'herb-root', 'produce', 'Ginger', 1, 10),
  ('turmeric', 'herb-root', 'produce', 'Turmeric', 1, 20),
  ('horseradish', 'herb-root', 'produce', 'Horseradish', 1, 30),

  ('mushrooms', 'mushroom', 'produce', 'Edible mushrooms', 1, 10),
  ('mushroom-white-button', 'mushrooms', 'produce', 'White button mushrooms', 2, 10),
  ('mushroom-brown-chestnut', 'mushrooms', 'produce', 'Brown chestnut mushrooms', 2, 20),
  ('mushroom-portobello', 'mushrooms', 'produce', 'Portobello mushrooms', 2, 30),
  ('mushroom-oyster', 'mushrooms', 'produce', 'Oyster mushrooms', 2, 40),
  ('mushroom-king-oyster', 'mushrooms', 'produce', 'King oyster mushrooms', 2, 50),
  ('mushroom-shiitake', 'mushrooms', 'produce', 'Shiitake mushrooms', 2, 60),
  ('mushroom-chanterelle', 'mushrooms', 'produce', 'Chanterelle mushrooms', 2, 70),
  ('mushroom-porcini-boletus', 'mushrooms', 'produce', 'Porcini and boletus mushrooms', 2, 80),
  ('mushroom-enoki', 'mushrooms', 'produce', 'Enoki mushrooms', 2, 90),
  ('mushroom-mixed-pack', 'mushrooms', 'produce', 'Mixed mushroom packs', 2, 100),
  ('mushroom-generic-unknown', 'mushrooms', 'produce', 'Generic mushrooms', 2, 110)
on conflict (id) do update set
  parent_id = excluded.parent_id,
  segment = excluded.segment,
  label = excluded.label,
  depth = excluded.depth,
  sort_order = excluded.sort_order,
  updated_at = now();
