import AxeBuilder from '@axe-core/playwright';
import { expect, test, type APIRequestContext } from '@playwright/test';
import type { AxeResults, Result } from 'axe-core';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const severityOrder = ['critical', 'serious', 'moderate', 'minor', 'unknown'] as const;
type Severity = (typeof severityOrder)[number];

type RouteAudit = {
  path: string;
  status: number | null;
  violations: Result[];
};

// Static app pages plus representative dynamic routes. The sitemap discovery below adds
// every crawlable catalog/SEO URL generated by the running Next app; this catalog keeps
// non-sitemap public pages such as /heatmap and personal localStorage routes in scope too.
const publicRouteCatalog = [
  '/',
  '/account',
  '/account/profile',
  '/alerts',
  '/ar',
  '/basket',
  '/basket-ideas',
  '/catalogue-savings',
  '/categories',
  '/categories/beverages',
  '/chain-coverage',
  '/chain-index',
  '/compare',
  '/compare-items',
  '/cookies',
  '/coupon-stacks',
  '/data-sources',
  '/deals',
  '/en',
  '/expiry-deals',
  '/favorites',
  '/favourites',
  '/fuel',
  '/heatmap',
  '/household',
  '/index/grocery',
  '/index-methodology',
  '/items',
  '/items/havredryck-choklad-7340083494406',
  '/list',
  '/login',
  '/map',
  '/meal-cost',
  '/meal-planner',
  '/nutrition-value',
  '/openprices-depth',
  '/pantry-planner',
  '/pharmacy',
  '/price-reports',
  '/privacy',
  '/product/havredryck-choklad-7340083494406',
  '/products',
  '/products/havredryck-choklad-7340083494406',
  '/savings-dashboard',
  '/scanner',
  '/screener',
  '/search',
  '/seasonal-calendar',
  '/settings',
  '/shopping-trips',
  '/so',
  '/store-coverage',
  '/stores',
  '/stores/0024-narlivs-sweden-543923929',
  '/sv',
  '/unit-price-alerts',
  '/watchlist',
  '/weekly-basket',
  '/widgets/grocery-index-ticker'
] as const;

function normalizePath(pathOrUrl: string, baseURL?: string) {
  const parsed = new URL(pathOrUrl, baseURL ?? 'http://127.0.0.1');
  const path = `${parsed.pathname}${parsed.search}`;
  return path === '' ? '/' : path;
}

function uniqueSorted(paths: Iterable<string>) {
  return [...new Set([...paths].map((path) => normalizePath(path)))].sort((a, b) => a.localeCompare(b));
}

async function discoverSitemapRoutes(request: APIRequestContext, baseURL?: string) {
  const response = await request.get('/sitemap.xml', { failOnStatusCode: false });
  if (!response.ok()) return [];

  const xml = await response.text();
  const locations = [...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((match) => match[1]);
  return locations
    .map((location) => normalizePath(location, baseURL))
    .filter((path) => !path.startsWith('/api'));
}

function severityOf(violation: Result): Severity {
  return severityOrder.includes(violation.impact as Severity) ? (violation.impact as Severity) : 'unknown';
}

function summarizeBySeverity(audits: RouteAudit[]) {
  return severityOrder.map((severity) => {
    const violations = audits.flatMap((audit) => audit.violations.filter((violation) => severityOf(violation) === severity));
    return {
      severity,
      rules: violations.length,
      nodes: violations.reduce((total, violation) => total + violation.nodes.length, 0)
    };
  });
}

function markdownCell(value: string | number) {
  return String(value).replace(/\|/g, '\\|').replace(/\n/g, '<br>');
}

function formatViolation(violation: Result) {
  const severity = severityOf(violation);
  const targets = violation.nodes
    .slice(0, 5)
    .map((node) => `    - \`${node.target.join(' ')}\`: ${node.failureSummary?.replace(/\s+/g, ' ').trim() ?? 'no failure summary'}`)
    .join('\n');
  const moreTargets = violation.nodes.length > 5 ? `\n    - …${violation.nodes.length - 5} more affected nodes` : '';

  return [
    `  - **${violation.id}** (${severity}) — ${violation.help}`,
    `    - Affected nodes: ${violation.nodes.length}`,
    `    - Guidance: ${violation.helpUrl}`,
    targets ? `${targets}${moreTargets}` : ''
  ].filter(Boolean).join('\n');
}

function buildReport(audits: RouteAudit[]) {
  const generatedAt = new Date().toISOString();
  const severitySummary = summarizeBySeverity(audits);
  const routesWithViolations = audits.filter((audit) => audit.violations.length > 0);
  const routeFailures = audits.filter((audit) => audit.status === null || audit.status >= 400);

  const summaryTable = [
    '| Severity | Rules | Affected nodes |',
    '| --- | ---: | ---: |',
    ...severitySummary.map((row) => `| ${markdownCell(row.severity)} | ${markdownCell(row.rules)} | ${markdownCell(row.nodes)} |`)
  ].join('\n');

  const routeSections = routesWithViolations.length === 0
    ? 'No axe violations were reported.'
    : routesWithViolations.map((audit) => [
      `### ${audit.path}`,
      '',
      ...severityOrder.flatMap((severity) => {
        const violations = audit.violations.filter((violation) => severityOf(violation) === severity);
        if (violations.length === 0) return [];
        return [`#### ${severity}`, ...violations.map(formatViolation)];
      })
    ].join('\n')).join('\n\n');

  const routeFailureSection = routeFailures.length === 0
    ? 'All audited routes returned a non-error response.'
    : routeFailures.map((audit) => `- ${audit.path}: ${audit.status ?? 'no response'}`).join('\n');

  return `# GroceryView accessibility audit report\n\nGenerated: ${generatedAt}\n\nAudited routes: ${audits.length}\nRoutes with axe violations: ${routesWithViolations.length}\n\n## Violations by severity\n\n${summaryTable}\n\n## Route load status\n\n${routeFailureSection}\n\n## Violations\n\n${routeSections}\n`;
}

test.describe('full public accessibility audit', () => {
  test('runs axe on every public route and writes a severity report', async ({ page, request, baseURL }) => {
    test.setTimeout(20 * 60 * 1000);

    const sitemapRoutes = await discoverSitemapRoutes(request, baseURL);
    const routes = uniqueSorted([...publicRouteCatalog, ...sitemapRoutes]);
    const audits: RouteAudit[] = [];

    for (const path of routes) {
      const response = await page.goto(path, { waitUntil: 'domcontentloaded' });
      const status = response?.status() ?? null;
      const axeResults: AxeResults = await new AxeBuilder({ page }).analyze();
      audits.push({ path, status, violations: axeResults.violations });
    }

    const report = buildReport(audits);
    await writeFile(join(process.cwd(), 'a11y-report.md'), report, 'utf8');

    expect(routes.length).toBeGreaterThan(0);
    expect(audits.filter((audit) => audit.status === null || audit.status >= 400)).toEqual([]);
  });
});
