from __future__ import annotations

from datetime import datetime, timezone

STOCKHOLM_STORES = [
    {
        "id": "store-willys-odenplan",
        "slug": "willys-odenplan",
        "name": "Willys Odenplan",
        "chain": "Willys",
        "city": "Stockholm",
        "district": "Odenplan",
        "latitude": 59.3428,
        "longitude": 18.0495,
    },
    {
        "id": "store-ica-kvantum-liljeholmen",
        "slug": "ica-kvantum-liljeholmen",
        "name": "ICA Kvantum Liljeholmen",
        "chain": "ICA",
        "city": "Stockholm",
        "district": "Liljeholmen",
        "latitude": 59.3107,
        "longitude": 18.0225,
    },
    {
        "id": "store-coop-farsta",
        "slug": "coop-farsta",
        "name": "Coop Farsta",
        "chain": "Coop",
        "city": "Stockholm",
        "district": "Farsta",
        "latitude": 59.2405,
        "longitude": 18.0947,
    },
    {
        "id": "store-hemkop-sodermalm",
        "slug": "hemkop-sodermalm",
        "name": "Hemköp Södermalm",
        "chain": "Hemköp",
        "city": "Stockholm",
        "district": "Södermalm",
        "latitude": 59.3151,
        "longitude": 18.0712,
    },
    {
        "id": "store-lidl-sveavagen",
        "slug": "lidl-sveavagen",
        "name": "Lidl Sveavägen",
        "chain": "Lidl",
        "city": "Stockholm",
        "district": "Norrmalm",
        "latitude": 59.3378,
        "longitude": 18.0617,
    },
]

HERO_PRODUCTS = [
    {
        "id": "product-arlamilk-1l",
        "slug": "arla-milk-1l",
        "ean": "7310865000013",
        "name": "Arla Milk 1L",
        "brand": "Arla",
        "category": "dairy",
        "unit": "liter",
        "unit_size": 1.0,
    },
    {
        "id": "product-eggs-12",
        "slug": "eggs-12-pack",
        "ean": "7310865000020",
        "name": "Eggs 12-pack",
        "brand": "Garant",
        "category": "eggs",
        "unit": "package",
        "unit_size": 12.0,
    },
    {
        "id": "product-butter-500g",
        "slug": "butter-500g",
        "ean": "7310865000037",
        "name": "Butter 500g",
        "brand": "Arla",
        "category": "dairy",
        "unit": "package",
        "unit_size": 0.5,
    },
    {
        "id": "product-coffee-450g",
        "slug": "coffee-450g",
        "ean": "7310865000044",
        "name": "Coffee 450g",
        "brand": "Zoégas",
        "category": "coffee",
        "unit": "package",
        "unit_size": 0.45,
    },
    {
        "id": "product-pasta-500g",
        "slug": "pasta-500g",
        "ean": "7310865000051",
        "name": "Pasta 500g",
        "brand": "Barilla",
        "category": "pantry",
        "unit": "package",
        "unit_size": 0.5,
    },
    {
        "id": "product-rice-1kg",
        "slug": "rice-1kg",
        "ean": "7310865000068",
        "name": "Rice 1kg",
        "brand": "Ica",
        "category": "pantry",
        "unit": "package",
        "unit_size": 1.0,
    },
    {
        "id": "product-bananas-1kg",
        "slug": "bananas-1kg",
        "ean": "7310865000075",
        "name": "Bananas 1kg",
        "brand": "Fresh",
        "category": "fruit",
        "unit": "kg",
        "unit_size": 1.0,
    },
    {
        "id": "product-toilet-paper-8",
        "slug": "toilet-paper-8-rolls",
        "ean": "7310865000082",
        "name": "Toilet Paper 8 rolls",
        "brand": "Lambi",
        "category": "household paper",
        "unit": "package",
        "unit_size": 8.0,
    },
]

RETAILER_PRICE_SNAPSHOT = {
    "willys-odenplan": {
        "arla-milk-1l": {"price_amount": 13.9, "price_type": "promotion", "confidence": 0.91, "label": "high"},
        "eggs-12-pack": {"price_amount": 34.9, "price_type": "regular", "confidence": 0.88, "label": "high"},
        "butter-500g": {"price_amount": 54.9, "price_type": "promotion", "confidence": 0.9, "label": "high"},
        "coffee-450g": {"price_amount": 49.9, "price_type": "promotion", "confidence": 0.87, "label": "high"},
    },
    "ica-kvantum-liljeholmen": {
        "arla-milk-1l": {"price_amount": 14.9, "price_type": "regular", "confidence": 0.84, "label": "high"},
        "eggs-12-pack": {"price_amount": 36.9, "price_type": "regular", "confidence": 0.82, "label": "high"},
        "coffee-450g": {"price_amount": 54.9, "price_type": "regular", "confidence": 0.83, "label": "high"},
        "bananas-1kg": {"price_amount": 24.9, "price_type": "regular", "confidence": 0.8, "label": "high"},
    },
    "coop-farsta": {
        "pasta-500g": {"price_amount": 12.9, "price_type": "promotion", "confidence": 0.79, "label": "medium"},
        "rice-1kg": {"price_amount": 24.9, "price_type": "regular", "confidence": 0.8, "label": "high"},
        "toilet-paper-8-rolls": {"price_amount": 69.9, "price_type": "regular", "confidence": 0.77, "label": "medium"},
    },
}

FETCHED_AT = datetime(2026, 5, 19, 12, 0, tzinfo=timezone.utc).isoformat()
