FETCHED_AT = "2026-05-19T10:00:00+00:00"

STOCKHOLM_STORES = [
    {
        "id": "store-ica-odenplan",
        "slug": "ica-odenplan",
        "name": "ICA Odenplan",
        "chain": "ICA",
        "city": "Stockholm",
        "district": "Vasastan",
        "latitude": 59.3429,
        "longitude": 18.0495,
    },
    {
        "id": "store-coop-sodermalm",
        "slug": "coop-sodermalm",
        "name": "Coop Sodermalm",
        "chain": "Coop",
        "city": "Stockholm",
        "district": "Sodermalm",
        "latitude": 59.3166,
        "longitude": 18.0711,
    },
    {
        "id": "store-willys-kungsholmen",
        "slug": "willys-kungsholmen",
        "name": "Willys Kungsholmen",
        "chain": "Willys",
        "city": "Stockholm",
        "district": "Kungsholmen",
        "latitude": 59.3337,
        "longitude": 18.0319,
    },
    {
        "id": "store-hemkop-city",
        "slug": "hemkop-city",
        "name": "Hemkop City",
        "chain": "Hemkop",
        "city": "Stockholm",
        "district": "Norrmalm",
        "latitude": 59.3326,
        "longitude": 18.0649,
    },
    {
        "id": "store-lidl-hammarby",
        "slug": "lidl-hammarby",
        "name": "Lidl Hammarby",
        "chain": "Lidl",
        "city": "Stockholm",
        "district": "Hammarby Sjostad",
        "latitude": 59.3028,
        "longitude": 18.1029,
    },
]

HERO_PRODUCTS = [
    {
        "id": "product-oat-milk",
        "slug": "oat-milk-1l",
        "ean": "0735000000001",
        "name": "Oat Milk 1L",
        "brand": "Oatly",
        "category": "dairy_alt",
        "unit": "liter",
        "unit_size": 1.0,
    },
    {
        "id": "product-arabica-coffee",
        "slug": "arabica-coffee-450g",
        "ean": "0735000000002",
        "name": "Arabica Coffee 450g",
        "brand": "Zoegas",
        "category": "coffee",
        "unit": "kg",
        "unit_size": 0.45,
    },
    {
        "id": "product-bananas",
        "slug": "bananas-1kg",
        "ean": "0735000000003",
        "name": "Bananas",
        "brand": "Garant",
        "category": "fruit",
        "unit": "kg",
        "unit_size": 1.0,
    },
    {
        "id": "product-pasta",
        "slug": "spaghetti-500g",
        "ean": "0735000000004",
        "name": "Spaghetti 500g",
        "brand": "Barilla",
        "category": "pantry",
        "unit": "kg",
        "unit_size": 0.5,
    },
    {
        "id": "product-eggs",
        "slug": "eggs-12-pack",
        "ean": "0735000000005",
        "name": "Eggs 12-pack",
        "brand": "Kronagg",
        "category": "dairy",
        "unit": "package",
        "unit_size": 1.0,
    },
    {
        "id": "product-minced-beef",
        "slug": "minced-beef-500g",
        "ean": "0735000000006",
        "name": "Minced Beef 500g",
        "brand": "Scan",
        "category": "meat",
        "unit": "kg",
        "unit_size": 0.5,
    },
    {
        "id": "product-tomatoes",
        "slug": "crushed-tomatoes-400g",
        "ean": "0735000000007",
        "name": "Crushed Tomatoes 400g",
        "brand": "Mutti",
        "category": "pantry",
        "unit": "kg",
        "unit_size": 0.4,
    },
    {
        "id": "product-yogurt",
        "slug": "greek-yogurt-1kg",
        "ean": "0735000000008",
        "name": "Greek Yogurt 1kg",
        "brand": "Arla",
        "category": "dairy",
        "unit": "kg",
        "unit_size": 1.0,
    },
]

RETAILER_PRICE_SNAPSHOT = {
    "coop-sodermalm": {
        "arabica-coffee-450g": {"price_amount": 62.9, "confidence": 0.94, "price_type": "regular", "label": "high"},
        "bananas-1kg": {"price_amount": 24.9, "confidence": 0.98, "price_type": "promotion", "label": "verified"},
        "oat-milk-1l": {"price_amount": 22.9, "confidence": 0.92, "price_type": "regular", "label": "high"},
        "spaghetti-500g": {"price_amount": 18.9, "confidence": 0.89, "price_type": "regular", "label": "high"},
    },
    "hemkop-city": {
        "crushed-tomatoes-400g": {"price_amount": 19.9, "confidence": 0.91, "price_type": "regular", "label": "high"},
        "eggs-12-pack": {"price_amount": 41.9, "confidence": 0.87, "price_type": "member", "label": "medium"},
        "greek-yogurt-1kg": {"price_amount": 39.9, "confidence": 0.93, "price_type": "promotion", "label": "high"},
        "minced-beef-500g": {"price_amount": 58.9, "confidence": 0.9, "price_type": "regular", "label": "high"},
    },
    "ica-odenplan": {
        "bananas-1kg": {"price_amount": 26.9, "confidence": 0.97, "price_type": "regular", "label": "verified"},
        "eggs-12-pack": {"price_amount": 44.9, "confidence": 0.91, "price_type": "regular", "label": "high"},
        "oat-milk-1l": {"price_amount": 23.9, "confidence": 0.95, "price_type": "regular", "label": "high"},
        "spaghetti-500g": {"price_amount": 16.9, "confidence": 0.88, "price_type": "promotion", "label": "medium"},
    },
    "lidl-hammarby": {
        "bananas-1kg": {"price_amount": 22.9, "confidence": 0.86, "price_type": "promotion", "label": "medium"},
        "crushed-tomatoes-400g": {"price_amount": 14.9, "confidence": 0.88, "price_type": "regular", "label": "medium"},
        "greek-yogurt-1kg": {"price_amount": 34.9, "confidence": 0.84, "price_type": "regular", "label": "medium"},
        "minced-beef-500g": {"price_amount": 54.9, "confidence": 0.82, "price_type": "promotion", "label": "medium"},
    },
    "willys-kungsholmen": {
        "arabica-coffee-450g": {"price_amount": 59.9, "confidence": 0.9, "price_type": "member", "label": "high"},
        "crushed-tomatoes-400g": {"price_amount": 15.9, "confidence": 0.87, "price_type": "regular", "label": "medium"},
        "oat-milk-1l": {"price_amount": 21.9, "confidence": 0.9, "price_type": "regular", "label": "high"},
        "spaghetti-500g": {"price_amount": 17.9, "confidence": 0.86, "price_type": "regular", "label": "medium"},
    },
}
