import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const reportDate = (process.env.REPORT_DATE || new Date().toISOString().slice(0, 10)).slice(0, 10);
const resultsDir = join(root, 'docs', 'test-results');
const indexPath = join(root, 'docs', 'testing', 'INDEX.md');
const reportPath = join(resultsDir, `${reportDate}.md`);

function env(name, fallback = 'not reported') {
  const value = process.env[name]?.trim();
  return value ? value : fallback;
}

function outcomeRow(label, value) {
  return `| ${label} | ${value} |`;
}

const runUrl = env('GITHUB_SERVER_URL', 'https://github.com') !== 'not reported' && env('GITHUB_REPOSITORY') !== 'not reported' && env('GITHUB_RUN_ID') !== 'not reported'
  ? `${env('GITHUB_SERVER_URL')}/${env('GITHUB_REPOSITORY')}/actions/runs/${env('GITHUB_RUN_ID')}`
  : 'not reported';

const report = `# CI test results — ${reportDate}

Generated by \`scripts/test-report.ts\` during the CI workflow. This report records the workflow outcomes for the run; detailed logs remain in GitHub Actions.

## Run metadata

| Field | Value |
| --- | --- |
${outcomeRow('Repository', env('GITHUB_REPOSITORY'))}
${outcomeRow('Workflow', env('GITHUB_WORKFLOW'))}
${outcomeRow('Run id', env('GITHUB_RUN_ID'))}
${outcomeRow('Run attempt', env('GITHUB_RUN_ATTEMPT'))}
${outcomeRow('Ref', env('GITHUB_REF_NAME', env('GITHUB_REF')))}
${outcomeRow('Commit', env('GITHUB_SHA'))}
${outcomeRow('Actor', env('GITHUB_ACTOR'))}
${outcomeRow('Run URL', runUrl)}

## Gate outcomes

| Gate | Outcome |
| --- | --- |
${outcomeRow('Install dependencies', env('INSTALL_OUTCOME'))}
${outcomeRow('Tests', env('TEST_OUTCOME'))}
${outcomeRow('Build workspaces', env('BUILD_OUTCOME'))}
${outcomeRow('Next profile bundle budget', env('PROFILE_BUNDLE_OUTCOME'))}
${outcomeRow('Web bundle PR summary', env('BUNDLE_PR_SUMMARY_OUTCOME'))}
${outcomeRow('Lighthouse performance budget', env('LIGHTHOUSE_OUTCOME'))}
${outcomeRow('Typecheck', env('TYPECHECK_OUTCOME'))}
${outcomeRow('Overall job status at report time', env('JOB_STATUS'))}

## Notes

- CI writes this dated report on every run with \`if: always()\` so failures still leave a test-results artifact.
- The generated markdown is uploaded as a workflow artifact together with \`docs/testing/INDEX.md\`.
`;

mkdirSync(resultsDir, { recursive: true });
mkdirSync(join(root, 'docs', 'testing'), { recursive: true });
writeFileSync(reportPath, report, 'utf8');

const startMarker = '<!-- test-results:start -->';
const endMarker = '<!-- test-results:end -->';
const linkLine = `- [${reportDate} CI test results](../test-results/${reportDate}.md)`;
let index = '';
try {
  index = readFileSync(indexPath, 'utf8');
} catch {
  index = '# GroceryView testing index\n\nDated CI test-result reports are generated during GitHub Actions runs.\n\n';
}

if (!index.includes(startMarker) || !index.includes(endMarker)) {
  index = `${index.trim()}\n\n## CI test results\n\n${startMarker}\n${endMarker}\n`;
}

const before = index.slice(0, index.indexOf(startMarker) + startMarker.length);
const after = index.slice(index.indexOf(endMarker));
const existingBlock = index.slice(index.indexOf(startMarker) + startMarker.length, index.indexOf(endMarker));
const existingLinks = existingBlock
  .split('\n')
  .map((line) => line.trim())
  .filter((line) => line.startsWith('- [') && line !== linkLine);
const nextLinks = [linkLine, ...existingLinks].slice(0, 30);
const nextIndex = `${before}\n${nextLinks.join('\n')}\n${after}`;
writeFileSync(indexPath, nextIndex.endsWith('\n') ? nextIndex : `${nextIndex}\n`, 'utf8');

console.log(`Wrote ${reportPath}`);
console.log(`Updated ${indexPath}`);
