import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const resultsDir = join(root, 'docs', 'test-results');
const indexPath = join(root, 'docs', 'testing', 'INDEX.md');
const runDate = (process.env.TEST_REPORT_DATE || process.env.GITHUB_RUN_STARTED_AT || new Date().toISOString()).slice(0, 10);
const reportPath = join(resultsDir, `${runDate}.md`);

function status(name: string) {
  return process.env[name] || 'not_run';
}

function runUrl() {
  const server = process.env.GITHUB_SERVER_URL;
  const repo = process.env.GITHUB_REPOSITORY;
  const runId = process.env.GITHUB_RUN_ID;
  return server && repo && runId ? `${server}/${repo}/actions/runs/${runId}` : '';
}

function shortSha() {
  return (process.env.GITHUB_SHA || '').slice(0, 12) || 'unknown';
}

mkdirSync(resultsDir, { recursive: true });
mkdirSync(join(root, 'docs', 'testing'), { recursive: true });

const rows = [
  ['Tests', status('TEST_STEP_OUTCOME')],
  ['Build', status('BUILD_STEP_OUTCOME')],
  ['Next profile bundle budget', status('BUNDLE_STEP_OUTCOME')],
  ['Lighthouse performance budget', status('LIGHTHOUSE_STEP_OUTCOME')],
  ['Typecheck', status('TYPECHECK_STEP_OUTCOME')]
];
const overall = rows.every(([, outcome]) => outcome === 'success' || outcome === 'skipped') ? 'success' : 'failed';
const url = runUrl();

writeFileSync(reportPath, `# CI test results: ${runDate}

- Workflow: ${process.env.GITHUB_WORKFLOW || 'CI'}
- Run: ${process.env.GITHUB_RUN_NUMBER || 'local'}${url ? ` ([open run](${url}))` : ''}
- Ref: ${process.env.GITHUB_REF_NAME || 'local'}
- Commit: ${shortSha()}
- Overall: **${overall}**

| Check | Outcome |
|---|---|
${rows.map(([check, outcome]) => `| ${check} | ${outcome} |`).join('\n')}
`, 'utf8');

const reports = readdirSync(resultsDir)
  .filter((file) => /^\d{4}-\d{2}-\d{2}\.md$/.test(file))
  .sort()
  .reverse();

writeFileSync(indexPath, `# Testing results index

Generated by \`.github/workflows/ci.yml\` via \`scripts/test-report.ts\`.

${reports.map((file) => `- [${file.replace(/\.md$/, '')}](../test-results/${file})`).join('\n') || '- No CI result reports generated yet.'}
`, 'utf8');

console.log(`Wrote ${reportPath} and ${indexPath}`);
