import Link from 'next/link';
import { Card, Eyebrow, PageShell, SourceCoverage, TopSpreads } from '@/components/data-ui';
import { watchlistAlertBoard, watchlistAlertInputs } from '@/lib/demo-data';

function priceSource(productId: string) {
  return watchlistAlertInputs.products.find((product) => product.productId === productId)?.source ?? 'visible price row';
}

export default function WatchlistPage() {
  return (
    <PageShell>
      <Eyebrow>Watchlist price alerts</Eyebrow>
      <h1 className="mt-2 text-4xl font-black tracking-tight">Tracked products with notification-ready alerts</h1>
      <p className="mt-3 max-w-3xl text-lg leading-8 text-slate-700">
        This page calls buildWatchlistAlerts with visible price rows, then runs planNotifications so push and email rows respect user preferences and quiet-hour rules.
      </p>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr_1fr]">
        <Card>
          <p className="text-sm font-black uppercase tracking-[0.2em] text-slate-500">Watched products</p>
          <p className="mt-2 text-5xl font-black text-slate-950">{watchlistAlertBoard.coverage.watchedProducts}</p>
          <p className="mt-3 font-semibold text-slate-700">filtered against {watchlistAlertBoard.coverage.eligiblePriceRows} visible price rows.</p>
        </Card>
        <Card>
          <p className="text-sm font-black uppercase tracking-[0.2em] text-slate-500">Active alerts</p>
          <p className="mt-2 text-5xl font-black text-emerald-800">{watchlistAlertBoard.alerts.length}</p>
          <p className="mt-3 font-semibold text-slate-700">target price, Deal Score, and new-low signals only when core rules pass.</p>
        </Card>
        <Card>
          <p className="text-sm font-black uppercase tracking-[0.2em] text-slate-500">Planned notifications</p>
          <p className="mt-2 text-5xl font-black text-slate-950">{watchlistAlertBoard.plannedNotifications.length}</p>
          <p className="mt-3 font-semibold text-slate-700">email + push rows generated by planNotifications.</p>
        </Card>
      </div>

      <Card className="mt-6">
        <h2 className="text-2xl font-black">Alert board</h2>
        <div className="mt-4 space-y-3">
          {watchlistAlertBoard.alerts.map((alert, index) => (
            <Link className="block rounded-2xl border border-slate-200 p-4 hover:border-emerald-700" href={`/products/${alert.productId}`} key={`${alert.productId}-${alert.type}-${index}`}>
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <p className="text-xl font-black text-slate-950">{alert.productName}</p>
                  <p className="mt-1 text-sm text-slate-600">{alert.message}</p>
                  <p className="mt-1 text-sm font-semibold text-slate-700">{priceSource(alert.productId)}</p>
                </div>
                <div className="text-right">
                  <p className={`text-2xl font-black ${alert.severity === 'urgent' ? 'text-rose-700' : 'text-emerald-800'}`}>{alert.severity}</p>
                  <p className="text-sm font-semibold capitalize text-slate-600">{alert.type.replaceAll('_', ' ')}</p>
                </div>
              </div>
              <div className="mt-3 grid gap-2 text-sm text-slate-700 sm:grid-cols-3">
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">Metric: {alert.trigger.metric}</p>
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">Store: {alert.trigger.storeName}</p>
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">Value: {String(alert.trigger.value)}</p>
              </div>
            </Link>
          ))}
        </div>
      </Card>

      <Card className="mt-6">
        <h2 className="text-2xl font-black">Notification plan</h2>
        <p className="mt-2 text-sm font-semibold text-slate-600">{watchlistAlertBoard.coverage.caveat}</p>
        <div className="mt-4 grid gap-3 md:grid-cols-2">
          {watchlistAlertBoard.plannedNotifications.map((notification, index) => (
            <div className="rounded-2xl bg-slate-50 p-4" key={`${notification.title}-${notification.channel}-${index}`}>
              <p className="font-black">{notification.title}</p>
              <p className="mt-1 text-sm text-slate-600">{notification.channel} · {notification.type} · {notification.priority}</p>
              <p className="mt-2 text-sm font-semibold text-slate-700">Send at {notification.sendAt}</p>
            </div>
          ))}
        </div>
      </Card>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr]">
        <TopSpreads limit={5} />
        <SourceCoverage />
      </div>
    </PageShell>
  );
}
