import Link from 'next/link';
import { Card, Eyebrow, PageShell, SourceCoverage, TopSpreads } from '@/components/data-ui';
import { NotificationInboxActions } from '@/components/notification-inbox-actions';
import { babyDiaperPriceTracker, budgetEssentialsPriceDropAlerts, dealHunterNewProductPriceDropAlerts, watchlistAlertBoard, watchlistAlertInputs, weeklyPersonalizedEmailDigest } from '@/lib/demo-data';
import { priceAlertThresholdPreferenceContract } from '@/lib/verified-data';
import { routeMetadata } from '@/lib/seo';

export function generateMetadata() {
  return routeMetadata('/watchlist');
}

function priceSource(productId: string) {
  return watchlistAlertInputs.products.find((product) => product.productId === productId)?.source ?? 'visible price row';
}

function formatSek(value: number) {
  return new Intl.NumberFormat('sv-SE', { style: 'currency', currency: 'SEK', maximumFractionDigits: 2 }).format(value);
}

export default function WatchlistPage() {
  return (
    <PageShell>
      <Eyebrow>Watchlist price alerts</Eyebrow>
      <h1 className="mt-2 text-4xl font-black tracking-tight">Tracked products with notification-ready alerts</h1>
      <p className="mt-3 max-w-3xl text-lg leading-8 text-slate-700">
        This page calls buildWatchlistAlerts with visible price rows, then runs planNotifications so push and email rows respect user preferences and quiet-hour rules.
      </p>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr_1fr]">
        <Card>
          <p className="text-sm font-black uppercase tracking-[0.2em] text-slate-500">Watched products</p>
          <p className="mt-2 text-5xl font-black text-slate-950">{watchlistAlertBoard.coverage.watchedProducts}</p>
          <p className="mt-3 font-semibold text-slate-700">filtered against {watchlistAlertBoard.coverage.eligiblePriceRows} visible price rows.</p>
        </Card>
        <Card>
          <p className="text-sm font-black uppercase tracking-[0.2em] text-slate-500">Active alerts</p>
          <p className="mt-2 text-5xl font-black text-emerald-800">{watchlistAlertBoard.alerts.length}</p>
          <p className="mt-3 font-semibold text-slate-700">target price, Deal Score, and new-low signals only when core rules pass.</p>
        </Card>
        <Card>
          <p className="text-sm font-black uppercase tracking-[0.2em] text-slate-500">Planned notifications</p>
          <p className="mt-2 text-5xl font-black text-slate-950">{watchlistAlertBoard.plannedNotifications.length}</p>
          <p className="mt-3 font-semibold text-slate-700">email + push rows generated by planNotifications.</p>
        </Card>
      </div>

      <Card className="mt-6">
        <h2 className="text-2xl font-black">Alert board</h2>
        <div className="mt-4 space-y-3">
          {watchlistAlertBoard.alerts.map((alert, index) => (
            <Link className="block rounded-2xl border border-slate-200 p-4 hover:border-emerald-700" href={`/products/${alert.productId}`} key={`${alert.productId}-${alert.type}-${index}`}>
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <p className="text-xl font-black text-slate-950">{alert.productName}</p>
                  <p className="mt-1 text-sm text-slate-600">{alert.message}</p>
                  <p className="mt-1 text-sm font-semibold text-slate-700">{priceSource(alert.productId)}</p>
                </div>
                <div className="text-right">
                  <p className={`text-2xl font-black ${alert.severity === 'urgent' ? 'text-rose-700' : 'text-emerald-800'}`}>{alert.severity}</p>
                  <p className="text-sm font-semibold capitalize text-slate-600">{alert.type.replaceAll('_', ' ')}</p>
                </div>
              </div>
              <div className="mt-3 grid gap-2 text-sm text-slate-700 sm:grid-cols-3">
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">Metric: {alert.trigger.metric}</p>
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">Store: {alert.trigger.storeName}</p>
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">Value: {String(alert.trigger.value)}</p>
              </div>
            </Link>
          ))}
        </div>
      </Card>


      <NotificationInboxActions />

      <Card className="mt-6 border-indigo-200 bg-indigo-50">
        <p className="text-sm font-black uppercase tracking-[0.2em] text-indigo-800">email digest</p>
        <h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">Weekly personalised email digest</h2>
        <p className="mt-3 max-w-3xl text-sm font-semibold leading-6 text-slate-700">
          {weeklyPersonalizedEmailDigest.subject} is assembled from watchlistAlerts produced by buildWatchlistAlerts and bestDeals produced by rankDealOpportunities, then passed through planNotifications with email-only preferences.
        </p>
        <div className="mt-4 grid gap-3 lg:grid-cols-3">
          <div className="rounded-2xl bg-white p-4 shadow-sm">
            <p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">watchlistAlerts</p>
            <p className="mt-1 text-4xl font-black text-indigo-900">{weeklyPersonalizedEmailDigest.watchlistAlerts.length}</p>
            <p className="mt-2 text-sm font-semibold text-slate-600">Private watched products, target-price hits, and stock-up opportunities.</p>
          </div>
          <div className="rounded-2xl bg-white p-4 shadow-sm">
            <p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">bestDeals</p>
            <p className="mt-1 text-4xl font-black text-indigo-900">{weeklyPersonalizedEmailDigest.bestDeals.length}</p>
            <p className="mt-2 text-sm font-semibold text-slate-600">Public ranked deal opportunities filtered by source confidence.</p>
          </div>
          <div className="rounded-2xl bg-white p-4 shadow-sm">
            <p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">email sends</p>
            <p className="mt-1 text-4xl font-black text-indigo-900">{weeklyPersonalizedEmailDigest.plannedEmails.length}</p>
            <p className="mt-2 text-sm font-semibold text-slate-600">{weeklyPersonalizedEmailDigest.channelDefault.maxFrequency} · one-click unsubscribe {weeklyPersonalizedEmailDigest.channelDefault.requiresOneClickUnsubscribe ? 'required' : 'not required'}.</p>
          </div>
        </div>
        <div className="mt-4 grid gap-4 lg:grid-cols-2">
          <div className="rounded-2xl border border-indigo-100 bg-white p-4">
            <h3 className="text-lg font-black text-slate-950">Watchlist section</h3>
            <div className="mt-3 space-y-2">
              {weeklyPersonalizedEmailDigest.watchlistAlerts.map((alert) => (
                <Link className="block rounded-2xl bg-indigo-50 p-3 text-sm font-semibold hover:bg-indigo-100" href={`/products/${alert.productId}`} key={`${alert.productId}-${alert.severity}`}>
                  <strong>{alert.productName}</strong><br />{alert.message}<br /><span className="text-slate-600">{alert.source}</span>
                </Link>
              ))}
            </div>
          </div>
          <div className="rounded-2xl border border-indigo-100 bg-white p-4">
            <h3 className="text-lg font-black text-slate-950">Best deals section</h3>
            <div className="mt-3 space-y-2">
              {weeklyPersonalizedEmailDigest.bestDeals.map((deal) => (
                <Link className="block rounded-2xl bg-indigo-50 p-3 text-sm font-semibold hover:bg-indigo-100" href={`/products/${deal.productId}`} key={`${deal.productId}-${deal.storeName}`}>
                  <strong>{deal.productName}</strong> · {deal.storeName}<br />{formatSek(deal.currentPrice)} now · Deal Score {deal.dealScore} · sourceConfidence {Math.round(deal.sourceConfidence * 100)}%
                </Link>
              ))}
            </div>
          </div>
        </div>
        <div className="mt-4 grid gap-3 md:grid-cols-2">
          {weeklyPersonalizedEmailDigest.plannedEmails.map((email, index) => (
            <div className="rounded-2xl bg-white p-4 text-sm font-semibold text-slate-700 shadow-sm" key={`${email.title}-${index}`}>
              <p className="font-black text-slate-950">{email.title}</p>
              <p className="mt-1">{email.channel} · {email.type} · sendAt {email.sendAt}</p>
              <p className="mt-2">{email.body}</p>
            </div>
          ))}
        </div>
        <p className="mt-4 rounded-2xl bg-white p-3 text-sm font-black text-indigo-950">{weeklyPersonalizedEmailDigest.coverage.caveat}</p>
      </Card>


      <Card className="mt-6 border-amber-200 bg-amber-50">
        <p className="text-sm font-black uppercase tracking-[0.2em] text-amber-800">{dealHunterNewProductPriceDropAlerts.persona}</p>
        <h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">New-product & price-drop alerts</h2>
        <p className="mt-3 max-w-3xl text-sm font-semibold leading-6 text-slate-700">
          Deal hunters get priceDropAlerts from buildWatchlistAlerts and newProductSignals from rankDealOpportunities output. A newProductSignals row is not a retailer launch claim; it only means the product newly surfaced in visible ranked deal rows.
        </p>
        <div className="mt-4 grid gap-4 lg:grid-cols-2">
          <div className="rounded-2xl border border-amber-100 bg-white p-4">
            <h3 className="text-lg font-black text-slate-950">priceDropAlerts</h3>
            <div className="mt-3 space-y-2">
              {dealHunterNewProductPriceDropAlerts.priceDropAlerts.map((alert) => (
                <Link className="block rounded-2xl bg-amber-50 p-3 text-sm font-semibold hover:bg-amber-100" href={`/products/${alert.productId}`} key={`${alert.productId}-${alert.type}`}>
                  <strong>{alert.productName}</strong><br />{alert.message}<br />
                  <span className="text-slate-600">{alert.triggerMetric}: {String(alert.triggerValue)} · {alert.source}</span>
                </Link>
              ))}
            </div>
          </div>
          <div className="rounded-2xl border border-amber-100 bg-white p-4">
            <h3 className="text-lg font-black text-slate-950">newProductSignals</h3>
            <div className="mt-3 space-y-2">
              {dealHunterNewProductPriceDropAlerts.newProductSignals.map((signal) => (
                <Link className="block rounded-2xl bg-amber-50 p-3 text-sm font-semibold hover:bg-amber-100" href={`/products/${signal.productId}`} key={`${signal.productId}-${signal.storeName}`}>
                  <strong>{signal.productName}</strong> · {signal.storeName}<br />{formatSek(signal.currentPrice)} · Deal Score {signal.dealScore}<br />
                  <span className="text-slate-600">sourceConfidence {Math.round(signal.sourceConfidence * 100)}% · {signal.discoverySignal}</span>
                </Link>
              ))}
            </div>
          </div>
        </div>
        <div className="mt-4 grid gap-3 md:grid-cols-3">
          {dealHunterNewProductPriceDropAlerts.plannedNotifications.slice(0, 3).map((notification, index) => (
            <div className="rounded-2xl bg-white p-4 text-sm font-semibold text-slate-700 shadow-sm" key={`${notification.title}-${index}`}>
              <p className="font-black text-slate-950">{notification.title}</p>
              <p className="mt-1">{notification.channel} · {notification.type} · {notification.priority}</p>
            </div>
          ))}
        </div>
        <p className="mt-4 rounded-2xl bg-white p-3 text-sm font-black text-amber-950">{dealHunterNewProductPriceDropAlerts.coverage.caveat}</p>
      </Card>

      <Card className="mt-6 border-purple-200 bg-purple-50">
        <p className="text-sm font-black uppercase tracking-[0.2em] text-purple-800">Account watchlist preferences</p>
        <h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">Custom price alert thresholds</h2>
        <p className="mt-3 max-w-3xl text-sm font-semibold leading-6 text-slate-700">
          No anonymous thresholds are stored or applied. Signed-in shoppers can save targetPrice and dealScoreMinimum preferences, then GroceryView passes those values into buildWatchlistAlerts before planNotifications applies channel and quiet-hour rules.
        </p>
        <div className="mt-4 grid gap-3 lg:grid-cols-4">
          {priceAlertThresholdPreferenceContract.thresholdTypes.map((threshold) => (
            <div className="rounded-2xl border border-purple-200 bg-white p-4" key={threshold.key}>
              <p className="text-lg font-black text-slate-950">{threshold.label}</p>
              <p className="mt-1 text-xs font-bold text-slate-600">{threshold.key}</p>
              <p className="mt-3 rounded-2xl bg-purple-100 p-3 text-sm font-semibold text-purple-950">{threshold.engineInput}</p>
              <p className="mt-2 text-xs font-semibold text-slate-600">{threshold.storedValue}</p>
            </div>
          ))}
        </div>
        <ul className="mt-4 space-y-2 text-sm font-semibold text-slate-700">
          {priceAlertThresholdPreferenceContract.guardrails.map((guardrail) => (
            <li key={guardrail}>• {guardrail}</li>
          ))}
        </ul>
      </Card>

      <Card className="mt-6">
        <h2 className="text-2xl font-black">Notification plan</h2>
        <p className="mt-2 text-sm font-semibold text-slate-600">{watchlistAlertBoard.coverage.caveat}</p>
        <div className="mt-4 grid gap-3 md:grid-cols-2">
          {watchlistAlertBoard.plannedNotifications.map((notification, index) => (
            <div className="rounded-2xl bg-slate-50 p-4" key={`${notification.title}-${notification.channel}-${index}`}>
              <p className="font-black">{notification.title}</p>
              <p className="mt-1 text-sm text-slate-600">{notification.channel} · {notification.type} · {notification.priority}</p>
              <p className="mt-2 text-sm font-semibold text-slate-700">Send at {notification.sendAt}</p>
            </div>
          ))}
        </div>
      </Card>

      <Card className="mt-6 border-emerald-200 bg-emerald-50">
        <p className="text-sm font-black uppercase tracking-[0.2em] text-emerald-800">{budgetEssentialsPriceDropAlerts.persona}</p>
        <h2 className="mt-2 text-2xl font-black">Essentials price-drop alerts</h2>
        <p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-700">
          This low-income tracker calls buildWatchlistAlerts for weekly essentials and keeps essentialCategory plus weeklyNeed visible so shoppers can prioritize staples before treats.
        </p>
        <div className="mt-4 grid gap-3 lg:grid-cols-3">
          {budgetEssentialsPriceDropAlerts.rows.map((row) => (
            <Link className="rounded-2xl border border-emerald-200 bg-white p-4 hover:border-emerald-700" href={`/products/${row.productId}`} key={row.productId}>
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <p className="text-lg font-black text-slate-950">{row.productName}</p>
                  <p className="mt-1 text-sm font-semibold text-slate-600">essentialCategory: {row.essentialCategory}</p>
                  <p className="mt-1 text-sm font-semibold text-slate-600">weeklyNeed: {row.weeklyNeed}</p>
                </div>
                <p className="text-2xl font-black text-emerald-800">{row.alertCount} alerts</p>
              </div>
              <div className="mt-3 grid gap-2 text-sm text-slate-700">
                <p className="rounded-2xl bg-emerald-100 p-3 font-semibold">Best {row.bestPrice} SEK</p>
                <p className="rounded-2xl bg-emerald-100 p-3 font-black text-emerald-900">Deal Score {row.dealScore}</p>
                <p className="rounded-2xl bg-slate-50 p-3 font-semibold">{row.source}</p>
              </div>
            </Link>
          ))}
        </div>
        <p className="mt-4 text-sm font-semibold text-slate-700">{budgetEssentialsPriceDropAlerts.coverage.caveat}</p>
      </Card>

      <Card className="mt-6 border-blue-200 bg-blue-50">
        <p className="text-sm font-black uppercase tracking-[0.2em] text-blue-800">{babyDiaperPriceTracker.persona}</p>
        <h2 className="mt-2 text-2xl font-black">Baby & diaper price tracking</h2>
        <p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-700">
          This family tracker calls buildWatchlistAlerts for diaper packs and exposes diaperUnitPrice so parents can compare price per diaper without estimating missing loyalty-wallet offers.
        </p>
        <div className="mt-4 grid gap-3 lg:grid-cols-2">
          {babyDiaperPriceTracker.rows.map((row) => (
            <Link className="rounded-2xl border border-blue-200 bg-white p-4 hover:border-blue-700" href={`/products/${row.productId}`} key={row.productId}>
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                  <p className="text-lg font-black text-slate-950">{row.productName}</p>
                  <p className="mt-1 text-sm font-semibold text-slate-600">{row.source}</p>
                </div>
                <p className="text-2xl font-black text-blue-800">{row.alertCount} alerts</p>
              </div>
              <div className="mt-3 grid gap-2 text-sm text-slate-700 sm:grid-cols-3">
                <p className="rounded-2xl bg-blue-100 p-3 font-semibold">Best {row.bestPrice} SEK</p>
                <p className="rounded-2xl bg-blue-100 p-3 font-semibold">diaperUnitPrice {row.diaperUnitPrice.toFixed(2)} SEK</p>
                <p className="rounded-2xl bg-emerald-50 p-3 font-black text-emerald-900">Deal Score {row.dealScore}</p>
              </div>
            </Link>
          ))}
        </div>
        <p className="mt-4 text-sm font-semibold text-slate-700">{babyDiaperPriceTracker.coverage.caveat}</p>
      </Card>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr]">
        <TopSpreads limit={5} />
        <SourceCoverage />
      </div>
    </PageShell>
  );
}
